### ISSUE TITLE
Configure Elasticsearch Service from external server instead of local[v5]

### ISSUE THREAD

**Issue by vasanth1896** [reportportal/reportportal#1095]
https://github.com/reportportal/reportportal/issues/764#issue-532095841

Please refer the above issue for details. Was able to configure ES_HOST until 5.2.3v, but after upgrading to 5.3v its not working/ Kindly help on this. If i am doing anything wrong in compose file, please let me know.

```
analyzer:
    image: 'service-auto-analyzer:5.3.0'
    environment:
      LOGGING_LEVEL: info
      AMQP_URL: amqp://rabbitmq:rabbitmq@rabbitmq:5672
    environment:
      - ES_HOSTS=<HOST_NAME>
    #depends_on:
      #- rabbitmq
      #- elasticsearch
    restart: always
```
