### ISSUE TITLE
Installing ReportPortal on 2 VMs - App & DB

### ISSUE THREAD

**Issue by talgreen1** [reportportal/reportportal#1436]
Hello,
According to this [article](https://github.com/reportportal/reportportal/wiki/Production-Ready-set-and-Deployment-Customization) it is recommended to use 2 VMs - one for the APP and one for the DB & storage.

Can you please specify what needed to be changed in the docker-compose file in order to achieve this?
Do I need to install anything manually on the DB vm?

Thanks,
Tal.

**Comment by irynakozak2** [comment]
@Cyberglamdring Hleb, could you please help here?

**Comment by Cyberglamdring** [comment]
Hello @talgreen1,

You can separate [docker-compose.yml](https://github.com/reportportal/reportportal/blob/master/docker-compose.yml). The first one should contain [`postgres`](https://github.com/reportportal/reportportal/blob/master/docker-compose.yml#L118) and [`migration`](https://github.com/reportportal/reportportal/blob/master/docker-compose.yml#L105), the second one should contain all other services.

To connect the database, add a new variable `RP_DB_PORT` for the services `jobs`, `uat`, `api`. For example:

```yaml
  api: 
    environment:
      RP_DB_HOST: <DB_VM_IP>
      RP_DB_PORT: <EXPOSED_PORT_DROM_DM_VM>
      RP_DB_USER: rpuser
      RP_DB_PASS: <MY_STRONG_PASSWORD>
      RP_DB_NAME: reportportal

```

❗️Make sure you fill all database variables in the second docker compose file.
