### ISSUE TITLE
Regarding Downgrade of RP V5.4 to V5.3.5

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1461]
@evjlobanova : I observed a few issues recently when I upgraded to RP version 5.4, However, there was an additional upgrade in the version of my automation tool and the version of my chrome browser. I wanted to narrow down the problem and understand the module (RP, Automation or browser upgrade) which introduced the issues for me.
Hence, I wanted to **move back to V5.3.5 from V5.4** for my prod setup until I conclude on the above activity. Can you suggest to me the clean steps I could follow to achieve the same without losing my data and baselines?

**Comment by evjlobanova** [comment]
@Cyberglamdring  I guess you can advice something regarding this?

**Comment by priyankachaturvedi30** [comment]
@Cyberglamdring : Can you help me in this context ?

**Comment by Cyberglamdring** [comment]
Hello @priyankachaturvedi30,

To deploy 5.3.5, you need to downgrade the database to 5.3.5 by [Migration Service](https://github.com/reportportal/migrations)

0. ❗️Create a backup of your database.

1. Create simple docker-compose:
```YAML
version: '2'
services:
  migrations:
    image: reportportal/migrations:5.4.0
    environment:
      POSTGRES_USER: rpuser
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: StrongDatabasePassword
      POSTGRES_SERVER: databaseIP
      POSTGRES_DB: reportportal
    restart: on-failure
```

2.  Run Service:

```BASH
docker-compose run --rm migrations down N
```

Where `N` = `*.down.sql` scritps from folder [migrations](https://github.com/reportportal/migrations/tree/5.4.0/migrations) installed version `5.4.0` minus requerd version `5.3.5`. `N = 47 - 25 = 22`
