### ISSUE TITLE
How To Address log4j Vulnerability

### ISSUE THREAD

**Issue by Rickdickulous** [reportportal/reportportal#1897]
In using Report Portal 5.7.0 our security team reported a log4j vulnerability on the VM for elasticsearch.

I tried increasing the elasticsearch docker image version to 7.17.7 which worked the first time I booted up the instance, but when I restarted the service the elasticsearch container came up unhealthy and the VM locks up. It seems like the CPU is maxed out after that. This happened when I used our existing data in the 'data' folder as well as when creating a bare instance with an empty 'data' folder.

Can anyone provide some guidance on how I should be updating the elasticsearch version, or how else I can address the log4j vulnerability being flagged?

**Comment by Rickdickulous** [comment]
I may have solved this by adding the `entrypoint` and `command` sections below to remove the Jndi class. #1613 says this class may actually be used. I've been running this without any issues yet. Are there any potential issues with removing this class in this way?

```
elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "logger.level=INFO"
      - "xpack.security.enabled=true"
      - "ELASTIC_PASSWORD=elastic1q2w3e"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
      # ports:
      # - "9200:9200"
      
    # added entrypoint and command to mimic elasticsearch 7.10.1 container behavior: https://hub.docker.com/layers/library/elasticsearch/7.10.1/images/sha256-a7b465c42780a7e92892878ea30941b427d691698a100454dee7296140cdb889?context=explore
    entrypoint: ["/tini", "--", "/usr/local/bin/docker-entrypoint.sh"]
    command:  >
      sh -c "zip -d /usr/share/elasticsearch/lib/log4j-core-*.jar org/apache/logging/log4j/core/lookup/JndiLookup.class ||
             docker-entrypoint.sh"
    
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://elastic:elastic1q2w3e@localhost:9200/_cat/health"]
    restart: always
```
