### ISSUE TITLE
s3 Bucket configuration instead of MinIO leads to 403

### ISSUE THREAD

**Issue by dmckernanacv** [reportportal/reportportal#1947]
**Describe the bug**
Report Portal API and UAT both fail to start when providing AWS s3 endpoint / credentials using the kubernetes helm chart values:

```yaml
minio:
  enabled: true
  installdep:
    enable: false
  accesskey: <value of key>
  secretkey: <value of key>
  region: us-east-1
  endpoint: https://<bucketname>.s3.amazonaws.com
```

As explained in the docs, this should connect directly to an s3 bucket, however in the attached log file `(line 103+)` I get a bunch of 403 forbiddens

[report-portal-reportportal-api-7dbc4d6744-6jlc8.log](https://github.com/reportportal/reportportal/files/10887249/report-portal-reportportal-api-7dbc4d6744-6jlc8.log)

That said, using the `aws` cli with the same credentials works to copy files to the bucket. 

I was wondering if there was documentation I was missing I would really like to eliminate minio as as dependency.

**Expected behavior**
ReportPortal api and uat start successfully using a valid s3 bucket as a binary store.

**Versions:**
 - OS, Browser: linux(kubernetes)
 - Version of RP: 5.7.4

**Comment by irynakozak2** [comment]
@dmckernanacv Hi!
Could you please try the following configuration for S3?

For the next services you need to have the following environment variables:

uat:
` 
- name: DATASTORE_TYPE
   value: s3
- name: DATASTORE_S3_BUCKETPREFIX
   value: <your_bucket_prefix>
- name: DATASTORE_S3_REGION
   value: eu-central-1
- name: DATASTORE_S3_DEFAULTBUCKETNAME
   value: <your_default_bucket_name>
- name: DATASTORE_S3_ACCESSKEY
   value: <your_access_key>
- name: DATASTORE_S3_SECRETKEY
   value: <your_secret_key>
`

api:
`
- name: RP_BINARYSTORE_TYPE
   value: s3
- name: RP_BINARYSTORE_S3_BUCKETPREFIX
   value: <your_bucket_prefix>
- name: RP_BINARYSTORE_S3_DEFAULTBUCKETNAME
   value: <your_default_bucket_name>
- name: RP_BINARYSTORE_S3_REGION
   value: eu-central-1
- name: RP_BINARYSTORE_S3_ACCESSKEY
   value: <your_access_key>
- name: RP_BINARYSTORE_S3_SECRETKEY
   value: <your_secret_key>
`

jobs:
`
- name: DATASTORE_TYPE
   value: s3
- name: DATASTORE_S3_BUCKETPREFIX
   value: <your_bucket_prefix>
- name: DATASTORE_S3_REGION
   value: eu-central-1
- name: DATASTORE_S3_DEFAULTBUCKETNAME
   value: <your_default_bucket_name>
- name: DATASTORE_S3_ACCESSKEY
   value: <your_access_key>
- name: DATASTORE_S3_SECRETKEY
   value: <your_secret_key>
`

minio:
`
  enabled: false
  installdep:
    enable: false
  endpoint: http://minio.reportportal.svc.cluster.local:9000
  endpointshort: minio.reportportal.svc.cluster.local:9000
  region: ""
  bucketPrefix: ""
  defaultBucketName: ""
  integrationSaltPath: ""
`

For the minio service we are using `enabled: false `value which means that S3 is enabled instead of MinIO.
Waiting for your reply.

**Comment by dmckernanacv** [comment]
This still appears to be incorrect, I swapped out with the suggested config above, and it still looks like its trying to make connections with file names as the s3 bucket name, eg: `https://prj-keystore.s3.amazonaws.com` (by the way, `us-east-1` does not work, but `us-standard` does).

Instead I would expect my bucket name with a path to the file like `https://acv-device-farm-dev.s3.amazonaws.com/prj-keystore/secret-integration-salt`

Attached is the full log file

[report-portal-reportportal-api-777969f987-qp45c.log](https://github.com/reportportal/reportportal/files/10934717/report-portal-reportportal-api-777969f987-qp45c.log)

And heres the binarystore env vars with aws keys redacted (btw, there seems to be no way to get these vars injected with the helm chart)
```yaml

            - name: RP_BINARYSTORE_TYPE
              value: s3
            - name: RP_BINARYSTORE_S3_BUCKETPREFIX
              value: prj-
            - name: RP_BINARYSTORE_S3_DEFAULTBUCKETNAME
              value: acv-report-portal-dev
            - name: RP_BINARYSTORE_S3_REGION
              value: us-standard
            - name: RP_BINARYSTORE_S3_ACCESSKEY
              value: <redacted>
            - name: RP_BINARYSTORE_S3_SECRETKEY
              value: <redacted>
            - name: RP_BINARYSTORE_S3_ENDPOINT
              value: https://acv-device-farm-dev.s3.amazonaws.com
```
