### ISSUE TITLE
Google Storage (s3) support

### ISSUE THREAD

**Issue by azhurbilo** [reportportal/reportportal#1998]
**Describe the solution you'd like**

could you describe solution or documentation how connect to google storage (s3 compatibility mode) https://cloud.google.com/storage/docs/interoperability

all components should have support for overriding s3 endpoint to https://storage.googleapis.com

**Is your feature request related to a problem? Please describe.**

problem: additional support for Minio (reduced stability because of additional component), we expect to work directly with Google Cloud Storage (s3 mode)

----

I see comment about S3 connection (not google cloud storage)
https://github.com/reportportal/reportportal/issues/1947#issuecomment-1462046447

are "DATASTORE_S3_ENDPOINT" / "RP_BINARYSTORE_S3_ENDPOINT" / "DATASTORE_S3_ENDPOINT" env vars supported by reportportal components?

example

```
uat:
- name: DATASTORE_TYPE
  value: s3
- name: DATASTORE_S3_ENDPOINT
   value: https://storage.googleapis.com
   ***

api:
- name: RP_BINARYSTORE_TYPE
  value: s3
- name: RP_BINARYSTORE_S3_ENDPOINT
   value: https://storage.googleapis.com
   ***
  
jobs:
- name: DATASTORE_TYPE
  value: s3
- name: DATASTORE_S3_ENDPOINT
  value: https://storage.googleapis.com
  ***
 ```
