### ISSUE TITLE
Mess of ES property syntax in docker-compose file

### ISSUE THREAD

**Issue by Kanaduchi** [reportportal/reportportal#2022]
**Describe the bug**
The mess of ES hosts in the docker-compose file leads to confusion. Currently each service has its own syntax from ES property:
```
metrics-gatherer: 
      ES_HOST: http://elasticsearch:9200
      ES_USER: username
      ES_PASSWORD: password
analyzer_train:
      ES_HOSTS: http://username:password@elasticsearch:9200
analyzer:
      ES_HOSTS: http://username:password@elasticsearch:9200
jobs:
      RP_ELASTICSEARCH_HOST: http://elasticsearch:9200
      RP_ELASTICSEARCH_USERNAME: username
      RP_ELASTICSEARCH_PASSWORD: password
```

What should I do if my Elastic has anonymous access? I tried to remove RP_ELASTICSEARCH_USERNAME but get an error:
```
jobs Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'rp.elasticsearch.username' in value "${rp.elasticsearch.username}"
```

**Expected behavior**
All containers should have a common property name. Possibility to use Elastic without specifying username and password

**Versions:**
 - all versions starting from 5.7.3
