### ISSUE TITLE
API service is not restarting in case of unhealthy state

### ISSUE THREAD

**Issue by sramasudha** [reportportal/reportportal#2064]
**Describe the bug**
...
API service container is not restarting in case of unhealthy state
**Expected behavior**
...
API service container should restart in case of unhealthy state

** Reproduction steps **
Easily reproduced if you give some wrong port instead of 8585 in the health check URL of API service in docker compose file. 
**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP 5.8.0

**Comment by irynakozak2** [comment]
@IvanKustau @APiankouski hello everyone, could you please check?

**Comment by sramasudha** [comment]
@IvanKustau @APiankouski  any update for us?

**Comment by yevheniilavrenchuk** [comment]
@irynakozak2 @IvanKustau @APiankouski
Faced this as well today, after upgrading to 5.8.0.
UI just hangs on Loading... API container restart helps though, 
![image](https://github.com/reportportal/reportportal/assets/137056044/6a5f987f-0bde-4148-8255-cdc82c53543e)

**Comment by IvanKustau** [comment]
@yevheniilavrenchuk @sramasudha I can suggest you replace healthcheck for api service in docker-compose with this:
    healthcheck:
      test: curl -f http://0.0.0.0:8585/health
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 60s

**Comment by thereisnotime** [comment]
@IvanKustau does not work for me

**Comment by IvanKustau** [comment]
@thereisnotime These errors shouldn't stop the app from running. Is the service-api still in unhealthy state?

**Comment by thereisnotime** [comment]
@IvanKustau everything seems to be up and healthy:
![image](https://github.com/reportportal/reportportal/assets/37583483/322f0509-e347-4202-9f0f-b7c8866ed0ba)

```
NAME                              IMAGE                                                  COMMAND                  SERVICE             CREATED             STATUS                  
          PORTS
reportportal-analyzer-1           reportportal/service-auto-analyzer:5.7.5               "/venv/bin/uwsgi --h…"   analyzer            7 minutes ago       Up 4 minutes (healthy)            5001/tcp
reportportal-analyzer_train-1     reportportal/service-auto-analyzer:5.7.5               "/venv/bin/uwsgi --h…"   analyzer_train      7 minutes ago       Up 4 minutes (healthy)            5001/tcp
reportportal-api-1                reportportal/service-api:5.8.0                         "/bin/sh -c ./start.…"   api                 7 minutes ago       Up 4 minutes (health: starting)   8080/tcp
reportportal-elasticsearch-1      docker.elastic.co/elasticsearch/elasticsearch:7.10.1   "/tini -- /usr/local…"   elasticsearch       7 minutes ago       Up 6 minutes (healthy)            9200/tcp, 9300/tcp
reportportal-index-1              reportportal/service-index:5.8.0                       "./app"                  index               7 minutes ago       Up 6 minutes            
          8080/tcp
reportportal-jobs-1               reportportal/service-jobs:5.8.0                        "/bin/sh -c ./start.…"   jobs                6 minutes ago       Up 4 minutes (healthy)            8080/tcp
reportportal-metrics-gatherer-1   reportportal/service-metrics-gatherer:5.7.4            "/venv/bin/uwsgi --h…"   metrics-gatherer    7 minutes ago       Up 6 minutes (healthy)            5000/tcp
reportportal-minio-1              minio/minio:RELEASE.2020-10-27T04-03-55Z               "/usr/bin/docker-ent…"   minio               7 minutes ago       Up 6 minutes (healthy)            9000/tcp
reportportal-postgres-1           postgres:12-alpine                                     "docker-entrypoint.s…"   postgres            7 minutes ago       Up 6 minutes (healthy)            5432/tcp
reportportal-rabbitmq-1           bitnami/rabbitmq:3.10.8-debian-11-r7                   "/opt/bitnami/script…"   rabbitmq            7 minutes ago       Up 6 minutes (healthy)            4369/tcp, 5551-5552/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp
reportportal-uat-1                reportportal/service-authorization:5.8.0               "/bin/sh -c ./start.…"   uat                 7 minutes ago       Up 6 minutes (healthy)            8080/tcp
reportportal-ui-1                 reportportal/service-ui:5.8.0                          "/docker-entrypoint.…"   ui                  7 minutes ago       Up 6 minutes            
          8080/tcp
```

**Comment by thereisnotime** [comment]
@IvanKustau changing the health check and after few restarts of the API + changing the storage type of jobs/api and uat, increasing PG limits and changing permissions of the Windows folder for ES seems to make it work (even with the errors I have provided in my previous posts). Adding my compose files here:

reportportal
```yaml
version: '3'
# TODO: Move secrets of services to .env
# NOTE:
# You can generate a custom docker compose file automatically on http://reportportal.io/download (Step 2)
# This is example of Docker Compose for ReportPortal
# Do not forget to configure data volumes for production usage
# Execute 'docker-compose -f docker-compose.yml -p reportportal up -d --force-recreate' --build
# to start all containers in daemon mode
# Where:
#      '-f docker-compose.yml' -- specifies this compose file
#      '-p reportportal' -- specifies container's prefix (project name)
#      '-d' -- enables daemon mode
#      '--force-recreate' -- forces re-recreating of all containers
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    networks:
      - traefik
    volumes:
      # - elasticsearch:/usr/share/elasticsearch/data
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "logger.level=INFO"
      - "xpack.security.enabled=true"
      - "ELASTICSEARCH_USERNAME=${ES_MASTER_USER}"
      - "ELASTIC_PASSWORD=${ES_MASTER_PASSWORD}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://${ES_MASTER_USER}:${ES_MASTER_PASSWORD}@localhost:9200/_cat/health"]
    restart: always

  ## An analyzer instance for main functionality, don't forget to use the same storage settings (either MinIO, or filesystem) for analyzer_train
  analyzer: 
    image: reportportal/service-auto-analyzer:5.7.5
    networks:
      - traefik
    environment:
      LOGGING_LEVEL: info
      AMQP_EXCHANGE_NAME: ${RMQ_EXCHANGE}
      AMQP_VIRTUAL_HOST: ${RMQ_VHOST}
      AMQP_URL: amqp://${RMQ_MASTER_USER}:${RMQ_MASTER_PASSWORD}@rabbitmq:5672
      ES_HOSTS: http://${ES_MASTER_USER}:${ES_MASTER_PASSWORD}@elasticsearch:9200
      MINIO_SHORT_HOST: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    depends_on:
      elasticsearch:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: always
  
  ## An analyzer instance for training, don't forget to setup the same storage (either MinIO, or filesystem) as for main analyzer
  analyzer_train:
    image: reportportal/service-auto-analyzer:5.7.5
    networks:
      - traefik
    environment:
      LOGGING_LEVEL: info
      AMQP_EXCHANGE_NAME: ${RMQ_EXCHANGE}
      AMQP_VIRTUAL_HOST: ${RMQ_VHOST}
      AMQP_URL: amqp://${RMQ_MASTER_USER}:${RMQ_MASTER_PASSWORD}@rabbitmq:5672
      ES_HOSTS: http://${ES_MASTER_USER}:${ES_MASTER_PASSWORD}@elasticsearch:9200
      MINIO_SHORT_HOST: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      INSTANCE_TASK_TYPE: train
      UWSGI_WORKERS: 1
    depends_on:
      elasticsearch:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: always
 
  ## Metrics service for analyzing how analyzer is working and manage retrained models
  metrics-gatherer: 
    image: reportportal/service-metrics-gatherer:5.7.4
    networks:
      - traefik
    environment:
      LOGGING_LEVEL: info
      ES_HOST: http://elasticsearch:9200
      ES_USER: ${ES_MASTER_USER}
      ES_PASSWORD: ${ES_MASTER_PASSWORD}
      POSTGRES_USER: "${POSTGRES_MASTER_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_MASTER_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_MAIN_DB}"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
      ALLOWED_START_TIME: "22:00"
      ALLOWED_END_TIME: "08:00"
      #TZ: Europe/Minsk you can change a timezone like this to specify when metrics are gathered
      AMQP_URL: amqp://${RMQ_MASTER_USER}:${RMQ_MASTER_PASSWORD}@rabbitmq:5672
      AMQP_VIRTUAL_HOST: ${RMQ_VHOST}
    depends_on:
      - elasticsearch
    restart: always

  # ## Initial reportportal db schema. Run once.
  migrations:
    image: reportportal/migrations:5.8.0
    networks:
      - traefik
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_MAIN_DB}
      POSTGRES_USER: ${POSTGRES_MASTER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_MASTER_PASSWORD}
    restart: on-failure

  postgres:
    image: postgres:12-alpine
    networks:
      - traefik
    shm_size: '512m'
    environment:
      POSTGRES_USER: ${POSTGRES_MASTER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_MASTER_PASSWORD}
      POSTGRES_DB: ${POSTGRES_MAIN_DB}
    volumes:
      ## For unix host
      # - ./data/postgres:/var/lib/postgresql/data
      ## For windows host
       - postgres:/var/lib/postgresql/data
    ## If you need to access the DB locally. Could be a security risk to expose DB.
    command:
      -c checkpoint_completion_target=0.9
      -c work_mem=128MB
      -c wal_writer_delay=20ms
      -c synchronous_commit=off
      -c wal_buffers=32MB
      -c min_wal_size=2GB
      -c max_wal_size=4GB
      -c max_connections=400
      -c shared_buffers=80MB
    ## Optional, for SSD Data Storage. If you are using the HDD, set up this command to '2'
    #  -c effective_io_concurrency=200
    ## Optional, for SSD Data Storage. If you are using the HDD, set up this command to '4'
    #  -c random_page_cost=1.1
    ## Optional, can be scaled. Example for 4 CPU, 16GB RAM instance, where only the database is deployed
    #  -c max_worker_processes=4
    #  -c max_parallel_workers_per_gather=2
    #  -c max_parallel_workers=4
    #  -c shared_buffers=4GB
    #  -c effective_cache_size=12GB
    #  -c maintenance_work_mem=1GB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 120s
      retries: 10
    restart: always

  rabbitmq:
    image: bitnami/rabbitmq:3.10.8-debian-11-r7
    networks:
      - traefik
    environment:
      RABBITMQ_DEFAULT_USER: "${RMQ_MASTER_USER}"
      RABBITMQ_DEFAULT_PASS: "${RMQ_MASTER_PASSWORD}"
      RABBITMQ_DEFAULT_VHOST: "${RMQ_VHOST}"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      retries: 5
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: always

  uat:
    image: reportportal/service-authorization:5.8.0
    networks:
      - traefik
    environment:
      RP_DB_HOST: postgres
      RP_DB_USER: ${POSTGRES_MASTER_USER}
      RP_DB_PASS: ${POSTGRES_MASTER_PASSWORD}
      RP_DB_NAME: ${POSTGRES_MAIN_DB}
      DATASTORE_TYPE: filesystem
      DATASTORE_PATH: /data
      RP_BINARYSTORE_TYPE: minio 
      RP_BINARYSTORE_MINIO_ENDPOINT: http://minio:9000
      RP_BINARYSTORE_MINIO_ACCESSKEY: ${MINIO_ACCESS_KEY}
      RP_BINARYSTORE_MINIO_SECRETKEY: ${MINIO_SECRET_KEY}
      RP_SESSION_LIVE: 86400 #in seconds
      # RP_SAML_SESSION-LIVE: 4320
      ## The initial password for superadmin user on FIRST launch. If the password was changed from the UI, this value can't change the password on redeployments.
      RP_INITIAL_ADMIN_PASSWORD: "${RP_ADMIN_PASSWORD}"
    healthcheck:
      test: curl -f http://0.0.0.0:9999/health
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 60s
    labels:
      # Generic Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # Service Rewrites
      - "traefik.http.middlewares.uat-strip-prefix.stripprefix.prefixes=/uat"
      - "traefik.http.routers.uat.middlewares=uat-strip-prefix@docker"
      - "traefik.http.routers.uat.rule=PathPrefix(`/uat`)"
      # - "traefik.http.routers.uat.rule=Host(`${MAIN_DOMAIN}`)"
      # Service backend
      - "traefik.http.routers.uat.service=uat"
      - "traefik.http.services.uat.loadbalancer.server.port=9999"
      - "traefik.http.services.uat.loadbalancer.server.scheme=http"
      # Service SSL
      - "traefik.http.routers.uat.tls.certresolver=myresolver" # Use the resolver name from Traefik config
      - "traefik.http.routers.uat.entrypoints=websecure"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - uat:/data
    restart: always

  index:
    image: reportportal/service-index:5.8.0
    networks:
      - traefik
    environment:
      - LB_URL=http://traefik:8081
      - TRAEFIK_V2_MODE=true
    labels:
        # Generic Traefik
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        # Service Rewrites
        - "traefik.http.routers.index.rule=PathPrefix(`/`)"
        - "traefik.http.routers.index.service=index"
        # - "traefik.http.routers.index.rule=Host(`${MAIN_DOMAIN}`)"
        # Service Backend
        - "traefik.http.services.index.loadbalancer.server.port=8080"
        - "traefik.http.services.index.loadbalancer.server.scheme=http"
        # Service SSL
        - "traefik.http.routers.index.tls.certresolver=myresolver" # Use the resolver name from Traefik config
        - "traefik.http.routers.index.entrypoints=websecure"
    restart: always

  api:
    image: reportportal/service-api:5.8.0
    networks:
      - traefik
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      ## Double entry moves test logs from PostgreSQL to Elastic-type engines
      ## Ref: https://reportportal.io/blog/double-entry-in-5.7.2
      RP_ELASTICSEARCHLOGMESSAGE_HOST: true
      DATASTORE_TYPE: filesystem
      DATASTORE_PATH: /data
      RP_DB_HOST: postgres
      RP_DB_USER: ${POSTGRES_MASTER_USER}
      RP_DB_PASS: ${POSTGRES_MASTER_PASSWORD}
      RP_DB_NAME: ${POSTGRES_MAIN_DB}
      RP_AMQP_USER: ${RMQ_MASTER_USER}
      RP_AMQP_PASS: ${RMQ_MASTER_PASSWORD}
      RP_AMQP_APIUSER: ${RMQ_MASTER_USER}
      RP_AMQP_APIPASS: ${RMQ_MASTER_PASSWORD}
      RP_AMQP_ANALYZER-VHOST: ${RMQ_VHOST}
      RP_BINARYSTORE_TYPE: minio
      RP_BINARYSTORE_MINIO_ENDPOINT: http://minio:9000
      RP_BINARYSTORE_MINIO_ACCESSKEY: ${MINIO_ACCESS_KEY}
      RP_BINARYSTORE_MINIO_SECRETKEY: ${MINIO_SECRET_KEY}
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: info
      RP_REQUESTLOGGING: "false"
      MANAGEMENT_HEALTH_ELASTICSEARCH_ENABLED: "false"
      JAVA_OPTS: -Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp  -Dcom.sun.management.jmxremote.rmi.port=12349 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false  -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=0.0.0.0
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:8585/health || exit 1
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 60s
    labels:
      # Generic Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # Service - rewrites
      - "traefik.http.middlewares.api-strip-prefix.stripprefix.prefixes=/api" # Use for troubleshooting
      - "traefik.http.routers.api.middlewares=api-strip-prefix@docker"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)" # Add /api for troubleshooting
      # - "traefik.http.routers.api.rule=Host(`${MAIN_DOMAIN}`)"
      # Service Backend
      - "traefik.http.routers.api.service=api"
      - "traefik.http.services.api.loadbalancer.server.port=8585"
      - "traefik.http.services.api.loadbalancer.server.scheme=http"
      # Service SSL
      - "traefik.http.routers.api.tls.certresolver=myresolver" # Use the resolver name from Traefik config
      - "traefik.http.routers.api.entrypoints=websecure"
    volumes:
      - api:/data
    restart: always
    
  jobs:
    image: reportportal/service-jobs:5.8.0
    networks:
      - traefik
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      ## Double entry moves test logs from PostgreSQL to Elastic-type engines
      ## Ref: https://reportportal.io/blog/double-entry-in-5.7.2
      RP_ELASTICSEARCH_HOST: http://elasticsearch:9200
      RP_ELASTICSEARCH_USERNAME: ${ES_MASTER_USER}
      RP_ELASTICSEARCH_PASSWORD: ${ES_MASTER_PASSWORD}
      RP_DB_HOST: postgres
      RP_DB_USER: ${POSTGRES_MASTER_USER}
      RP_DB_PASS: ${POSTGRES_MASTER_PASSWORD}
      RP_DB_NAME: ${POSTGRES_MAIN_DB}
      RP_AMQP_USER: ${RMQ_MASTER_USER}
      RP_AMQP_PASS: ${RMQ_MASTER_PASSWORD}
      RP_AMQP_APIUSER: ${RMQ_MASTER_USER}
      RP_AMQP_APIPASS: ${RMQ_MASTER_PASSWORD}
      RP_AMQP_ANALYZER-VHOST: ${RMQ_VHOST}
      DATASTORE_TYPE: filesystem
      DATASTORE_PATH: /data
      # DATASTORE_MINIO_ENDPOINT: http://minio:9000
      # DATASTORE_MINIO_ACCESSKEY: ${MINIO_ACCESS_KEY}
      # DATASTORE_MINIO_SECRETKEY: ${MINIO_SECRET_KEY}
      RP_ENVIRONMENT_VARIABLE_CLEAN_ATTACHMENT_CRON: 0 0 */24 * * *
      RP_ENVIRONMENT_VARIABLE_CLEAN_LOG_CRON: 0 0 */24 * * *
      RP_ENVIRONMENT_VARIABLE_CLEAN_LAUNCH_CRON: 0 0 */24 * * *
      RP_ENVIRONMENT_VARIABLE_CLEAN_STORAGE_CRON: 0 0 */24 * * *
      RP_ENVIRONMENT_VARIABLE_STORAGE_PROJECT_CRON: 0 */5 * * * *
      RP_ENVIRONMENT_VARIABLE_CLEAN_STORAGE_CHUNKSIZE: 1000
      RP_PROCESSING_LOG_MAXBATCHSIZE: 2000
      RP_PROCESSING_LOG_MAXBATCHTIMEOUT: 6000
      RP_AMQP_MAXLOGCONSUMER: 1
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://0.0.0.0:8686/health || exit 1
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 60s
    labels:
      # Generic Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # Service Rewrites
      - traefik.http.middlewares.jobs-strip-prefix.stripprefix.prefixes=/jobs
      - traefik.http.routers.jobs.middlewares=jobs-strip-prefix@docker
      - traefik.http.routers.jobs.rule=PathPrefix(`/jobs`)
      # - traefik.http.routers.jobs.rule=Host(`${MAIN_DOMAIN}`)
      # Service Backend
      - traefik.http.routers.jobs.service=jobs
      - traefik.http.services.jobs.loadbalancer.server.port=8686
      - traefik.http.services.jobs.loadbalancer.server.scheme=http
      # Service SSL
      - "traefik.http.routers.jobs.tls.certresolver=myresolver" # Use the resolver name from Traefik config
      - "traefik.http.routers.jobs.entrypoints=websecure"
    volumes:
      - jobs:/data
    restart: always

  ui:
    image: reportportal/service-ui:5.8.0
    networks: 
      - traefik
    environment:
      - RP_SERVER_PORT=8080
    labels:
      # Generic Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # Service - rewrites
      - "traefik.http.middlewares.ui-strip-prefix.stripprefix.prefixes=/ui" # Use for troubleshooting
      - "traefik.http.routers.ui.middlewares=ui-strip-prefix@docker"
      - "traefik.http.routers.ui.rule=PathPrefix(`/ui`)" # Add /ui for troubleshooting
      # - "traefik.http.routers.ui.rule=Host(`${MAIN_DOMAIN}`)"
      # Service Backend
      - "traefik.http.routers.ui.service=ui"
      - "traefik.http.services.ui.loadbalancer.server.port=8080"
      - "traefik.http.services.ui.loadbalancer.server.scheme=http"
      # Service SSL
      - "traefik.http.routers.ui.tls.certresolver=myresolver" # Use the resolver name from Traefik config
      - "traefik.http.routers.ui.entrypoints=websecure"
    restart: always

  minio:
    image: minio/minio:RELEASE.2020-10-27T04-03-55Z
    networks: 
      - traefik
    volumes:
      ## For unix host
      # - ./data/storage:/data 
      ## For windows host
      - minio:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: always

## Docker volume for Windows host
volumes:
  postgres:
  minio:
  elasticsearch:
  rabbitmq:
  api:
  uat:
  jobs:

networks:
  traefik:
    external: true

````

traefik

```yaml
version: "3"
# TODO: Move traefik to volume (LE as well).
# TODO: Switch LE to prod.
# TODO: Add redirect to https.
services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    env_file:
      - .env
    networks:
      - "traefik"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      # Docker
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.traefik.address=:8081"
      # Certificate
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=${LE_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8081:8081"
    volumes:
      - "traefik:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      # Basic auth
      # - "traefik.http.middlewares.auth-basic.basicauth.users=znadmin:$$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      # - "traefik.http.routers.dashboard.middlewares=auth-basic"
      # API
      # - "traefik.http.routers.api.tls=true"
      # - "traefik.http.routers.api.service=api@internal"
      # - "traefik.http.routers.api.entrypoints=websecure"
      # - "traefik.http.routers.api.rule=Host(`${MAIN_DOMAIN}`) && PathPrefix(`/admin-traefik-api`)"
      # - "traefik.http.routers.api.tls.certresolver=myresolver"
      # - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/admin-traefik-api"
      # - "traefik.http.routers.api.middlewares=strip-api@docker"
      # Dashboard
      # - "traefik.http.routers.dashboard.tls=true"
      # - "traefik.http.routers.dashboard.service=dashboard@internal"
      # - "traefik.http.routers.dashboard.entrypoints=websecure"
      # - "traefik.http.routers.dashboard.rule=Host(`${MAIN_DOMAIN}`) && PathPrefix(`/admin-traefik`)"
      # - "traefik.http.routers.dashboard.tls.certresolver=myresolver"
      # - "traefik.http.middlewares.strip-dashboard.stripprefix.prefixes=/admin-traefik"
      # - "traefik.http.middlewares.dashboard-stripprefix-chain.chain.middlewares=dashboard-strip-prefix"
      # - "traefik.http.routers.dashboard.middlewares=strip-dashboard@docker"
      # API for dashboard
      # - "traefik.http.routers.dashboard-api.tls=true"
      # - "traefik.http.routers.dashboard-api.service=api@internal"
      # - "traefik.http.routers.dashboard-api.entrypoints=websecure"
      # - "traefik.http.routers.dashboard-api.rule=Host(`${MAIN_DOMAIN}`) && PathPrefix(`/api`)"
      # - "traefik.http.routers.dashboard-api.tls.certresolver=myresolver"
    restart: unless-stopped

networks:
  traefik:
    external: true

volumes:
  traefik:
```

prepare the folder for ES

```batch
mkdir data\elasticsearch
icacls "data\elasticsearch" /grant Everyone:F
```
