### ISSUE TITLE
***NEED help Not Able to Login as  admin access***

### ISSUE THREAD

**Issue by subha0990** [reportportal/reportportal#2072]
I deploy report portal by docker.
I am able to login as default user access.
I want to login as superadmin (Admin access)

superadmin /erebus

URL:- http://localhost:8080/ui/#login

Kindly help ASAP
![image](https://github.com/reportportal/agent-Python-RobotFramework/assets/140379815/ac959d0b-8243-4c06-8065-6d823b642adf)
=============Request URL:=======================
http://localhost:8080/uat/sso/oauth/token
Request Method:
POST
Status Code:
400 Bad Request
Remote Address:
[::1]:8080
Referrer Policy:
strict-origin-when-cross-origin
======payload===========
grant_type=password&username=superadmin&password=erebus
============response=============
{
    "errorCode": 4003,
    "message": "You do not have enough permissions. Bad credentials"
}

**Comment by subha0990** [comment]
any Update Team ?

**Comment by DzmitryHumianiuk** [comment]
@subha0990 
https://github.com/reportportal/reportportal/releases/tag/v23.1
says
**2. Technical Improvements:**
Initial Admin Passwords updates:
We’ve adjusted the existing approach: upon the initial installation and the first login of the SuperAdmin, they will be required to create a unique initial password, distinct from the default password provided in the ReportPortal installation documentation. Failure to do so will result in the Auth service not starting.

<img width="1246" alt="image" src="https://github.com/reportportal/reportportal/assets/11332788/450a5100-f3bd-446b-a1c5-e490b619f458">


https://github.com/reportportal/reportportal/blob/master/docker-compose.yml#L202C1-L203

```yml
 uat:
    image: reportportal/service-authorization:5.8.0
    # ports:
    #   - "9999:9999"
    environment:
      RP_DB_HOST: postgres
      RP_DB_USER: rpuser
      RP_DB_PASS: rppass
      RP_DB_NAME: reportportal
      RP_BINARYSTORE_TYPE: minio
      RP_BINARYSTORE_MINIO_ENDPOINT: http://minio:9000
      RP_BINARYSTORE_MINIO_ACCESSKEY: minio
      RP_BINARYSTORE_MINIO_SECRETKEY: minio123
      RP_SESSION_LIVE: 86400 # in seconds
      RP_SAML_SESSION-LIVE: 4320
📍->> ## The initial password for superadmin user on FIRST launch. If the password was changed from the UI, this value can't change the password on redeployments.
      RP_INITIAL_ADMIN_PASSWORD: "erebus"
    healthcheck:
      test: curl -f http://0.0.0.0:9999/health
      interval: 60s
      timeout: 30s
      retries: 10
      start_period: 60s
    labels:
      - "traefik.http.middlewares.uat-strip-prefix.stripprefix.prefixes=/uat"
      - "traefik.http.routers.uat.middlewares=uat-strip-prefix@docker"
      - "traefik.http.routers.uat.rule=PathPrefix(`/uat`)"
      - "traefik.http.routers.uat.service=uat"
      - "traefik.http.services.uat.loadbalancer.server.port=9999"
      - "traefik.http.services.uat.loadbalancer.server.scheme=http"
      - "traefik.expose=true"
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
```
