### ISSUE TITLE
How to Configure Reportportal on port 80 

### ISSUE THREAD

**Issue by Punyadotnet1** [reportportal/reportportal#2073]
Hi All, I need to configure Report portal on windows docker compose file with port 80.Kindly guide me .

**Comment by DzmitryHumianiuk** [comment]
change the port of expose accordingly.
please follow docker documentation for change of port expose.

on RP config find all 8080 ports and replace it with 80.
only this line should remain as `      - "80:8080" # HTTP exposed`
https://github.com/reportportal/reportportal/blob/master/docker-compose.yml#L20C35-L20C35


```yml
  gateway:
    image: traefik:v2.0.7
    ports:
📍    - "80:8080" # HTTP exposed
      - "8081:8081" # HTTP Administration exposed
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --providers.docker=true
      - --providers.docker.constraints=Label(`traefik.expose`, `true`)
📍    - --entrypoints.web.address=:80
      - --entrypoints.traefik.address=:8081
      - --api.dashboard=true
      - --api.insecure=true
    restart: always

```

https://github.com/reportportal/reportportal/blob/master/docker-compose.yml#L234
```yaml
  index:
    image: reportportal/service-index:5.8.0
    depends_on:
      gateway:
        condition: service_started
    environment:
      - LB_URL=http://gateway:8081
      - TRAEFIK_V2_MODE=true
    labels:
        - "traefik.http.routers.index.rule=PathPrefix(`/`)"
        - "traefik.http.routers.index.service=index"
📍      - "traefik.http.services.index.loadbalancer.server.port=80"
        - "traefik.http.services.index.loadbalancer.server.scheme=http"
        - "traefik.expose=true"
    restart: always
```

https://github.com/reportportal/reportportal/blob/master/docker-compose.yml#L341
```yml
  ui:
    image: reportportal/service-ui:5.8.0
    environment:
📍    - RP_SERVER_PORT=80
    labels:
      - "traefik.http.middlewares.ui-strip-prefix.stripprefix.prefixes=/ui"
      - "traefik.http.routers.ui.middlewares=ui-strip-prefix@docker"
      - "traefik.http.routers.ui.rule=PathPrefix(`/ui`)"
      - "traefik.http.routers.ui.service=ui"
📍   - "traefik.http.services.ui.loadbalancer.server.port=80"
      - "traefik.http.services.ui.loadbalancer.server.scheme=http"
      - "traefik.expose=true"
    restart: always
```
