### ISSUE TITLE
Auto-Analysis is not working Automatically on end of execution  complete

### ISSUE THREAD

**Issue by subha0990** [reportportal/reportportal#2077]
Hi Team,

Auto-Analysis is on from Project settings. On 2nd time Run auto-analysis is not working. Every time i need to apply manual analysis from Launch
![image](https://github.com/reportportal/reportportal/assets/140379815/11cc5ced-0f35-47f1-a1a0-4c558ee66b29)

Report-portal Build: 5.8.0
Logs [reportportal/service-auto-analyzer:5.7.5](https://github.com/reportportal/reportportal/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=#)
2023-08-03 23:19:24 2023-08-03 17:49:24,307 - analyzerApp - INFO - Starting waiting for AMQP connection
2023-08-03 23:19:24 2023-08-03 17:49:24,308 - analyzerApp.amqp - INFO - Try connect to /analyzer?heartbeat=600
2023-08-03 23:19:24 2023-08-03 17:49:24,312 - analyzerApp - ERROR - Amqp connection was not established
2023-08-03 23:19:24 2023-08-03 17:49:24,312 - analyzerApp - ERROR -
containers running fine
![image](https://github.com/reportportal/reportportal/assets/140379815/1b4418f8-9405-4ae7-80dc-6d0c558936d0)

Kindly help on this

**Comment by DzmitryHumianiuk** [comment]
@subha0990 your `service-auto-analyzer` can't connect to the rabbitMQ.

make sure your configuration is correct and present in every analyzer service

```yml
  ## An analyzer instance for main functionality, don't forget to use the same storage settings (either MinIO, or filesystem) for analyzer_train
  analyzer: 
    image: reportportal/service-auto-analyzer:5.7.5
    environment:
      LOGGING_LEVEL: info
📍    AMQP_EXCHANGE_NAME: analyzer-default
📍    AMQP_VIRTUAL_HOST: analyzer
📍    AMQP_URL: amqp://rabbitmq:rabbitmq@rabbitmq:5672
      ES_HOSTS: http://elastic:elastic1q2w3e@elasticsearch:9200
      MINIO_SHORT_HOST: minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    depends_on:
      elasticsearch:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: always
  
  ## An analyzer instance for training, don't forget to setup the same storage (either MinIO, or filesystem) as for main analyzer
  analyzer_train:
    image: reportportal/service-auto-analyzer:5.7.5
    environment:
      LOGGING_LEVEL: info
📍    AMQP_EXCHANGE_NAME: analyzer-default
📍    AMQP_VIRTUAL_HOST: analyzer
📍    AMQP_URL: amqp://rabbitmq:rabbitmq@rabbitmq:5672
      ES_HOSTS: http://elastic:elastic1q2w3e@elasticsearch:9200
      MINIO_SHORT_HOST: minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      INSTANCE_TASK_TYPE: train
      UWSGI_WORKERS: 1
    depends_on:
      elasticsearch:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: always
 
  ## Metrics service for analyzing how analyzer is working and manage retrained models
  metrics-gatherer: 
    image: reportportal/service-metrics-gatherer:5.7.4
    environment:
      LOGGING_LEVEL: info
      ES_HOST: http://elasticsearch:9200
      ES_USER: elastic
      ES_PASSWORD: elastic1q2w3e
      POSTGRES_USER: "rpuser"
      POSTGRES_PASSWORD: "rppass"
      POSTGRES_DB: "reportportal"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
      ALLOWED_START_TIME: "22:00"
      ALLOWED_END_TIME: "08:00"
      #TZ: Europe/Minsk you can change a timezone like this to specify when metrics are gathered
📍    AMQP_URL: amqp://rabbitmq:rabbitmq@rabbitmq:5672
📍    AMQP_VIRTUAL_HOST: analyzer
    depends_on:
      - elasticsearch
    restart: always

```

as an option expose the ports of rabbit:
```yaml
  rabbitmq:
    image: bitnami/rabbitmq:3.10.8-debian-11-r7
    ports:
📍    - "5672:5672"
📍    - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      retries: 5
    restart: always
```

and restart the whole docker-compose, not just specific services.
`docker-compose -p reportportal up -d --force-recreate`
