### ISSUE TITLE
SAML button is missing

### ISSUE THREAD

**Issue by Meszaros-Mark** [reportportal/reportportal#2246]
**Describe the bug**
The SAML button on the Login page is not appearing as intended after enabling the SAML for Azure.

**Expected behavior**
After the SAML Plugin enabled we should get a button to use the feature but it doesn't appear as expected.

**Screenshots**
<img width="503" alt="image" src="https://github.com/reportportal/reportportal/assets/162724459/8b7984b4-3b90-48e2-9684-33889bb6747e">

**Versions:**
 Browser: Chrome
 Client OS: Windows and Macos
 Server OS: Linux/X86_64

I can't see a version on the login page.

We are hosting report portal on AWS ECS separated into 11 different service/task:

- Proxy - traefik:v2.4
- API - reportportal/service-api:5.10.1
- UAT - reportportal/service-authorization:5.8.2
- UI - reportportal/service-ui:5.9.0
- METRICS - reportportal/service-metrics-gatherer:5.7.5
- JOBS - reportportal/service-jobs:5.8.2
- INDEX - reportportal/service-index:5.8.0
- ELASTICSEARCH - [docker.elastic.co/elasticsearch/elasticsearch:7.10.1](http://docker.elastic.co/elasticsearch/elasticsearch:7.10.1)
- ANALYZER SERVICE TRAIN - reportportal/service-auto-analyzer:5.7.5
- ANALYZER SERVICE - reportportal/service-auto-analyzer:5.7.6
- RABBITMQ - bitnami/rabbitmq:3.12.2-debian-11-r8

**Comment by Pink-Bumblebee** [comment]
@Meszaros-Mark , as I could see, you are using very mixed version of RP. I think this is possible reason why your issue happened.

**Comment by pmaus22** [comment]
Same issue here. The "Login with SAML" button is missing although the SAML Integration is configured. Additionally, the current versions of the RP services are not shown on the login page. For us, this occured after upgrading from RP version 23.2 to 24.1.

**Versions:**
Browser: Microsoft Edge
Client OS: Windows
Server OS: Debian GNU/Linux 11 (bullseye)

We are hosting ReportPortal via Docker Compose with this Compose File: https://raw.githubusercontent.com/reportportal/reportportal/v24.1/docker-compose.yml

Image versions:

- GATEWAY `traefik:v2.10.7`
- OPENSEARCH `opensearchproject/opensearch:2.11.0`
- POSTGRES `postgres:12.17-alpine3.17`
- RABBITMQ `bitnami/rabbitmq:3.12.2-debian-11-r8`
- INDEX `reportportal/service-index:5.11.0`
- UI `reportportal/service-ui:5.11.0`
- API `reportportal/service-api:5.11.0`
- UAT `reportportal/service-authorization:5.11.0`
- JOBS `reportportal/service-jobs:5.11.0`
- ANALYZER/ANALYZER-TRAIN `reportportal/service-auto-analyzer:5.11.0`
- METRICS-GATHERER `reportportal/service-metrics-gatherer:5.11.0`
- MIGRATIONS `reportportal/migrations:5.11.0`

Those are the pinned version for [RP Release v24.1](https://github.com/reportportal/reportportal/releases/tag/v24.1), so the issue can't be solely caused by mixed versions.

**Comment by pmaus22** [comment]
Screenshot for reference:
<img width="254" alt="image" src="https://github.com/reportportal/reportportal/assets/103952726/932d710a-dbda-45bc-b795-98da0744589f">

**Comment by Pink-Bumblebee** [comment]
@pmaus22 , something wrong with your services. Image has to look like this
![image](https://github.com/reportportal/reportportal/assets/145099680/8e7b0a5c-7515-4731-818a-08e3fa367cab)

**Comment by pmaus22** [comment]
Hi @Pink-Bumblebee, I checked our Compose File again and found the reason for our issue: A mismatch between the port values configured in the services `index` and `gateway`. Specifically, I had to make sure that the ports configured as the exposed port `"8081:8081" # Traefik dashboard` in the `gateway` service, the port in the `gateway` service command `--entrypoints.traefik.address=:8081` and the port in the `index` service environment variable `LB_URL: http://gateway:8081` are the same. After fixing the values everything works as expected.

Working config of the two services for reference
```yml
version: "3.8"
services:

  ## External dependencies

  gateway:
    image: traefik:v2.10.7@sha256:c5181ddf303f1ccfd4bd6d1d9c4867b0500efb6089a0f9ccb16612438f6e934f
    container_name: traefik
    logging: &logging
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "5"
    ports:
      - "443:443" # ReportPortal UI
      - "8081:8081" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/dynamic/traefik.toml
      - ./certs:/etc/certs/
    command:
      - --providers.docker=true
      - --providers.docker.constraints=Label(`traefik.expose`, `true`)
      - --entrypoints.traefik.address=:8081
      - --api.dashboard=true
      - --api.insecure=true
      # TLS/SSL
      - --providers.file.directory=/etc/traefik
      - --entrypoints.websecure.address=:443
      # Logs
      - --log.level=WARN
      # Accesslog
      - --accesslog=true
      - --accesslog.format=json
      - --accesslog.fields.defaultmode=keep
      - --accesslog.fields.headers.defaultmode=drop
      - --accesslog.fields.headers.names.ClientHost=keep
      - --accesslog.fields.headers.names.ClientUsername=keep
      - --accesslog.fields.headers.names.request_User-Agent=keep
      - --accesslog.fields.headers.names.TLSVersion=keep
      - --accesslog.fields.headers.names.TLSCipher=keep
      # Metrics
      - --metrics.prometheus=true
    networks:
      - reportportal
    restart: always

index:
    image: reportportal/service-index:5.11.0@sha256:336565651b1d4249b24eac5fd6eca093352b74e46800047fce8fc2810b0b3ee4
    container_name: reportportal-index
    logging:
      <<: *logging
    depends_on:
      gateway:
        condition: service_started
    environment:
      LB_URL: http://gateway:8081
      TRAEFIK_V2_MODE: 'true'
    healthcheck:
      test: wget -q --spider http://0.0.0.0:8080/health
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 10s
    labels:
      - "traefik.http.routers.index.rule=PathPrefix(`/`)"
      - "traefik.http.routers.index.service=index"
      - "traefik.http.services.index.loadbalancer.server.port=8080"
      - "traefik.http.services.index.loadbalancer.server.scheme=http"
      - "traefik.expose=true"
      - "traefik.http.routers.index.tls=true"
    networks:
      - reportportal
    restart: always
```
