### ISSUE TITLE
Rabbitmq docker container errors out due to  missing RABBITMQ_COMBINED_CERT_PATH 

### ISSUE THREAD

**Issue by tsundara** [reportportal/reportportal#2314]
Rabbitmq keeps restarting because 
```
rabbitmq 07:26:45.66 INFO  ==> Welcome to the Bitnami rabbitmq container
rabbitmq 07:26:45.66 INFO  ==> Subscribe to project updates by watching https://github.com/bitnami/containers
rabbitmq 07:26:45.66 INFO  ==> Submit issues and feature requests at https://github.com/bitnami/containers/issues
rabbitmq 07:26:45.67 INFO  ==> Upgrade to Tanzu Application Catalog for production environments to access custom-configured and pre-packaged software components. Gain enhanced features, including Software Bill of Materials (SBOM), CVE scan result reports, and VEX documents. To learn more, visit https://bitnami.com/enterprise
rabbitmq 07:26:45.67 INFO  ==>
rabbitmq 07:26:45.68 INFO  ==> ** Starting RabbitMQ setup **
rabbitmq 07:26:45.69 INFO  ==> Validating settings in RABBITMQ_* env vars..
rabbitmq 07:26:45.70 ERROR ==> The variable RABBITMQ_COMBINED_CERT_PATH must be set to either an existant file or a non-existant file in a writable directory.
```

Here is my docker-compose
```
  rabbitmq:
    image: bitnami/rabbitmq:3.13.2
    logging:
      <<: *logging
    ## Expose RabbitMQ
    # ports:
    #   - "5672:5672"
    #   - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: &rabbitmq_user rabbitmq
      RABBITMQ_DEFAULT_PASS: &rabbitmq_password rabbitmq
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: "true"
      ## @env RABBITMQ_PLUGINS define RabbitMQ plugins to be enabled
      ## rabbitmq_consistent_hash_exchange is required for the ReportPortal
      RABBITMQ_PLUGINS: rabbitmq_consistent_hash_exchange, rabbitmq_management, rabbitmq_auth_backend_ldap
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 30s
      retries: 5
    networks:
      - reportportal
    restart: always
```
...

**Screenshots**
![image](https://github.com/user-attachments/assets/29e630ce-bc80-4845-8af6-19494dced386)
