### ISSUE TITLE
DATASTORE_TYPE Environment variable does not persist

### ISSUE THREAD

**Issue by RobTurnerTL** [reportportal/reportportal#2541]
**Describe the bug**
We want to use an AWS S3 bucket and have looked at the documetattion here for S3 cloud storage https://reportportal.io/docs/installation-steps-advanced/FileStorageOptions/

we have made these changes to api, uat and jobs serives in our dockercompose file like so
```
  api:
    image: ${API_IMAGE-reportportal/service-api:5.13.4}
    build: ./service-api
    logging:
      <<: *logging
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
    environment:
      <<: *common-environment
      RP_FEATURE_FLAGS: singleBucket
      DATASTORE_TYPE: s3
      DATASTORE_REGION: eu-west-1
      DATASTORE_DEFAULTBUCKETNAME: <<OUR_BUCKET_NAME>>

# And so on....
```
When we deploy report portal all the above environment varibles appear to be set correctly except for DATASTORE_TYPE that for some reason is always "filesystem"

Here's some ourput when we query the machine to ask what the environment variables are.
```
sh-5.2$ docker exec reportportal-api-1 env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=7682cd83c294
DATASTORE_TYPE=filesystem
DATASTORE_REGION=eu-west-1
RP_ENVIRONMENT_VARIABLE_PATTERN-ANALYSIS_PREFETCH-COUNT=1
RP_AMQP_HOST=rabbitmq
MANAGEMENT_HEALTH_ELASTICSEARCH_ENABLED=false

... and so on ... 
```

We expect this to be the root cause of a error we get on some of the services, but please let us know if this could be caused by somthing else.
```
2025-05-06 15:49:01.449 ERROR 1 --- [nio-8585-exec-9] .r.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > Unable to load binary data by id 'Unable to findfile'
```

**Expected behavior**
The DATASTORE_TYPE environment variable should be whatever we have set it to. We suspect this to be the cause of an error we are having when 

**Versions:**
 - OS: Amazon Linux 2
 - Version Api Service 5.13.4, Auth and Jobs 5.13.1
