### ISSUE TITLE
Running Test using visual studio and upload test results to reportportal server, CI/CD, etc.

### ISSUE THREAD

**Issue by csekamal** [reportportal/reportportal#430]
Hi,
1. We are using nunit framework and C# for our reportportal implementation. We can run the tests using nunit3-console and the tests.dll file. However, we want to be able to run the tests (any or all) using Visual Studio IDE and be able to upload the results to the reportportal server but we were not able to do that. Is there any way to upload the test results to reportportal server while running the test(s) from Visual Studio?

2. Each time the reportportal server is restarted, it generates a new uuid. So we have to update all the projects with this new uuid to upload the test results to the reportportal. Is there a way, to lock down or disable the uuid when we restart the reportportal server so that it does not affect all the project?

3. See the issue below,
https://github.com/reportportal/reportportal/issues/408
Each time we restart the server in Dev, all the historical data is lost. How do we prevent this? What would be the steps for production deployment of reportportal? The available documentation for production deployment is not sufficient.

4. The need to use nunit3-console to run tests makes it little complicated to implement Continuous Integration and Delivery (CI/CD). There is very little documentation on reportportal site but that uses Jenkins. We are not using Jenkins and will be using only VSTS for CI/CD implementation. Can you provide specific instructions or case study to implement CI/CD using reportportal and nunit and C#?

Your help is greatly appreciated.
Thanks
A.K.

**Comment by DzmitryHumianiuk** [comment]
Hi @csekamal 

1. I guess there is no big difference in running it with command line and from Visual Studio. Probably you have to add some config params or executions with in Studio. The same relevant for Eclipse IDE.
Out team is in Java world. So maybe only @nvborisenko can help you with it.

2. This point belongs to point 3, and related to #408 as well.
ReportPortal saves your UUID forever. and don't change, until you press `Generate new UUID` on profile page.
UUID saved in database, for each user.
The problem you have: you loose your database each time you restart docker.
If you mongo image will not loose mount to database binaries of file system, then you will not loose UUID and won't loose any historical data.
So if you find answer for #408 - you will have answers for p2 and p3 here.

3. I guess it's specifics of docker running on windows. We really recommend to run it on linux based environments only.
Production deployment recommends to keep database on separate host.
This actually can be a key for your case.
Just deploy mongo separately. On the same PC or remote PC without docker. And connect RP to it.

4. There is no difference which CI tool you use. Jenkins, Bamboo, TeamCity or VSTS.
ReportPortal agent lives within thread of test execution, and can be triggered by any of mentioned above.
Best way to build proper pipeline:
- trigger test automation executions after code commit
- run all tests in parallel, collecting results in RP
- call merge/analyze functions via API (it can be just a `curl` call in command line as a after step)
- make API call to RP, to find out state of latest merged launch with code commit number from step1
- having passing rate decide GO or NO_GO for code change or build

**Comment by DzmitryHumianiuk** [comment]
@csekamal BTW, there are available steps, how to deploy it without 
http://reportportal.io/docs/Deploy-Without-Docker

**Comment by avarabyeu** [comment]
@csekamal could you please share with us your docker-compose file and command you use for restarting the server

**Comment by csekamal** [comment]
Hi avarabyeu,
The contents of my docker-compose.yml is below,
## This is example of Docker Compose for ReportPortal
## Do not forget to configure data volumes for production usage

## Execute 'docker-compose -p reportportal up -d --force-recreate'
## to start all containers in daemon mode
## Where:
##      '-p reportportal' -- specifies container's prefix (project name)
##      '-d' -- enables daemon mode
##      '--force-recreate' -- forces re-recreating of all containers

version: '2'

services:

  mongodb:
    image: mongo:3.4
#    ports:
#        - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    restart: always

  registry:
    image: consul:0.9.3
    volumes:
      - ./data/consul:/consul/data
#    ports:
#        - "8500:8500"
#        - "8300:8300"
#        - "53:8600/udp"
    command: "agent -server -bootstrap-expect=1 -ui -client 0.0.0.0  -raft-protocol=3"
    environment:
        - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    restart: always


  uat:
    image: reportportal/service-authorization:3.3.0
    #ports:
    #  - "9999:9999"
    depends_on:
      - mongodb
    environment:
      - RP_PROFILES=docker
      - RP_SESSION_LIVE=86400 #in seconds
#     - RP_MONGO_HOST=XXX
#     - RP_MONGO_PORT=27017
#     - RP_MONGO_DB_NAME=reportportal
#     - RP_MONGO_USER=XXX
#     - RP_MONGO_PASSWORD=XXX    
    restart: always

  gateway:
    image: fabiolb/fabio:1.5.2-go1.9
    ports:
      - "9998:9998" # GUI/management
      - "8080:9999" # HTTP exposed
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=registry:8500
      - FABIO_REGISTRY_CONSUL_REGISTER_NAME=gateway
      - FABIO_PROXY_ADDR=:9999;rt=300s;wt=300s
    restart: always

  index:
    image: reportportal/service-index:3.1.1
    environment:
      - RP_SERVER.PORT=8080
      - RP_CONSUL.TAGS=urlprefix-/
      - RP_CONSUL.ADDRESS=registry:8500
    depends_on:
       - registry
       - gateway
    restart: always

  api:
    image: reportportal/service-api:3.3.2
    depends_on:
      - mongodb
    environment:
      - RP_PROFILES=docker
      - RP_ISSUE_ANALYZER_DEPTH=4
      - JAVA_OPTS=-Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp
    # - RP_MONGO_HOST=XXX
    # - RP_MONGO_PORT=27017
    # - RP_MONGO_DB_NAME=reportportal
    # - RP_MONGO_USER=XXX
    # - RP_MONGO_PASSWORD=XXX
    restart: always

  ui:
    image: reportportal/service-ui:3.3.2
    environment:
      - RP_SERVER.PORT=8080
      - RP_CONSUL.TAGS=urlprefix-/ui opts strip=/ui
      - RP_CONSUL.ADDRESS=registry:8500
    restart: always

  jira:
    image: reportportal/service-jira:3.3.0
    environment:
      - RP_PROFILES=docker
#      - RP_MONGO_HOST=XXX
#      - RP_MONGO_PORT=27017
#      - RP_MONGO_DB_NAME=reportportal
#      - RP_MONGO_USER=XXX
#      - RP_MONGO_PASSWORD=XXX
    restart: always

#  rally:
#    image: reportportal/service-rally:3.3.0
#    environment:
#      - RP_PROFILES=docker
##      - RP_MONGO_HOST=XXX
##      - RP_MONGO_PORT=27017
##      - RP_MONGO_DB_NAME=reportportal
##      - RP_MONGO_USER=XXX
##      - RP_MONGO_PASSWORD=XXX
#    restart: always

To restart, I use the command,
docker-compose -p reportportal up -d --force-recreate

The problem of loosing the historical data happens when I restart my PC. I am planning to try installing mongo without docker in a separate machine as DzmitryHumianiuk mentioned, to see I can avoid loosing my data and uuid. I will update again after I am able to run RP using Mongo on a separate machine. Many thanks to both of you, DzmitryHumianiuk and avarabyeu.

In regards to running in command line and not in Visual Studio, its fine with us (automation group) but for QAs its kind difficult as they are not very comfortable or not that much technical to handle it in the command line. If we could run the subset of tests from Visual Studio and able to upload it on the rep server that would be really nice. But currently, I can only upload the test results if I run the test.dll using nunit3-console.exe.

Thanks
A.K.

**Comment by csekamal** [comment]
[docker-compose.pdf](https://github.com/reportportal/reportportal/files/2111292/docker-compose.pdf)
Attaching the docker-compose.yml file as copy/paste the file content looked a bit weird.

**Comment by DzmitryHumianiuk** [comment]
@csekamal don't use `--force-recreate` for a start.
it just wipes all data and configs for images.

Just `docker-compose -p reportportal up -d`

https://docs.docker.com/compose/reference/up/
```
    --force-recreate           Recreate containers even if their configuration
                               and image haven't changed.
```

**Comment by nvborisenko** [comment]
If you use `Visual Studio Test Run` task in VSTS or Visual studio, you might be interested in https://github.com/reportportal/agent-net-vstest
And example of integration: https://github.com/reportportal/example-net-vstest

**Comment by csekamal** [comment]
Hi @nvborisenko ,
We are using nunit and not Visual Studio Test Run. Right now, the only way, we can run the tests and upload the test result to reportportal is to run from the commandline,
>nunit3-console test.dll
If we run from the Visual Studio IDE then the tests run but cannot be uploaded to reportportal. Is there any way to run the tests from VS IDE and still be able to upload the test results to reportportal?
We followed the instructions as stated in the link below,
https://github.com/reportportal/agent-net-nunit
Thanks
A.K.

**Comment by nvborisenko** [comment]
@csekamal it will be possible when NunitAdapter will support user extensions. Vote there: https://github.com/nunit/nunit3-vs-adapter/issues/222

**Comment by csekamal** [comment]
Hi,
I have configured mongodb as a windows service. What lines do I have to comment or uncomment in docker-compose.yml to properly run reportportal inside the docker engine?
To configure mongodb as windows server, I installed mongodb then used the command,
mongod --logpath “C:\data\rp\log\mongo.log” --serviceName="RP_mongo" --dbpath “C:\data\rp” --directoryperdb –install
and then start the service by,
net start RP_mongo
I can see that mongodb service is running under windows services. I tried the below docker-compose.yml but I was not able to login using superadmin/erebus or default credentials.
The contents of my docker-compose.yml to start the containers are,
`## You can generate a custom docker compose file automatically on http://reportportal.io/download (Step 2)

## This is example of Docker Compose for ReportPortal
## Do not forget to configure data volumes for production usage

## Execute 'docker-compose -p reportportal up -d --force-recreate'
## to start all containers in daemon mode
## Where:
##      '-p reportportal' -- specifies container's prefix (project name)
##      '-d' -- enables daemon mode
##      '--force-recreate' -- forces re-recreating of all containers

version: '2'

services:

#  mongodb:
#    image: mongo:3.4
    #ports:
#        - "27017:27017"
#    volumes:
#      - ./data/mongo:/data/db
#    restart: always

  registry:
    image: consul:1.0.6
    volumes:
      - ./data/consul:/consul/data
    ports:
        - "8500:8500"
#        - "8300:8300"
#        - "53:8600/udp"
    command: "agent -server -bootstrap-expect=1 -ui -client 0.0.0.0"
    environment:
        - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    restart: always


  uat:
    image: reportportal/service-authorization:4.2.0
    #ports:
    #  - "9999:9999"
#    depends_on:
#      - mongodb
    environment:
      - RP_PROFILES=docker
      - RP_SESSION_LIVE=86400 #in seconds
      - RP_MONGO_URI=mongodb://localhost:27017
    restart: always

### Another option for gateway
### Can be used instead of traefik
#  gateway:
#    image: fabiolb/fabio:1.5.8-go1.10
#    ports:
#      - "9998:9998" # GUI/management
#      - "8080:9999" # HTTP exposed
#    environment:
#      - FABIO_REGISTRY_CONSUL_ADDR=registry:8500
#      - FABIO_REGISTRY_CONSUL_REGISTER_NAME=gateway
#      - FABIO_PROXY_ADDR=:9999;rt=300s;wt=300s
#    restart: always



  gateway:
    image: traefik:1.6.3
    ports:
      - "8080:8080" # HTTP exposed
#      - "8081:8081" # HTTP Administration exposed
    command:
      - --consulcatalog.endpoint=registry:8500
      - --defaultEntryPoints=http
      - --entryPoints=Name:http Address::8080
      - --web
      - --web.address=:8081
    restart: always

  index:
    image: reportportal/service-index:4.2.0
    environment:
      - RP_SERVER_PORT=8080
      - RP_PROXY_CONSUL=true
    depends_on:
       - registry
       - gateway
    restart: always

  api:
    image: reportportal/service-api:4.2.1
#    depends_on:
#      - mongodb
    environment:
      - RP_PROFILES=docker
      - JAVA_OPTS=-Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp
      - RP_MONGO_URI=mongodb://localhost:27017
    restart: always

  ui:
    image: reportportal/service-ui:4.2.2
    environment:
      - RP_SERVER.PORT=8080
      - RP_CONSUL.TAGS=urlprefix-/ui opts strip=/ui
      - RP_CONSUL.ADDRESS=registry:8500
    restart: always

  analyzer:
    image: reportportal/service-analyzer:4.2.0
    depends_on:
       - registry
       - gateway
       - elasticsearch
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    restart: always
    volumes:
        - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    ports:
#        - "9200:9200"

#  jira:
#    image: reportportal/service-jira:4.2.0
#    environment:
#      - RP_PROFILES=docker
#      - RP_MONGO_URI=mongodb://localhost:27017
#    restart: always

#  rally:
#    image: reportportal/service-rally:4.2.0
#    environment:
#      - RP_PROFILES=docker
#     - RP_MONGO_URI=mongodb://localhost:27017
#    restart: always`

Thanks
A.K.

**Comment by csekamal** [comment]
```
## You can generate a custom docker compose file automatically on http://reportportal.io/download (Step 2)

## This is example of Docker Compose for ReportPortal
## Do not forget to configure data volumes for production usage

## Execute 'docker-compose -p reportportal up -d --force-recreate'
## to start all containers in daemon mode
## Where:
##      '-p reportportal' -- specifies container's prefix (project name)
##      '-d' -- enables daemon mode
##      '--force-recreate' -- forces re-recreating of all containers

version: '2'

services:

#  mongodb:
#    image: mongo:3.4
    #ports:
#        - "27017:27017"
#    volumes:
#      - ./data/mongo:/data/db
#    restart: always

  registry:
    image: consul:1.0.6
    volumes:
      - ./data/consul:/consul/data
    ports:
        - "8500:8500"
#        - "8300:8300"
#        - "53:8600/udp"
    command: "agent -server -bootstrap-expect=1 -ui -client 0.0.0.0"
    environment:
        - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    restart: always


  uat:
    image: reportportal/service-authorization:4.2.0
    #ports:
    #  - "9999:9999"
#    depends_on:
#      - mongodb
    environment:
      - RP_PROFILES=docker
      - RP_SESSION_LIVE=86400 #in seconds
      - RP_MONGO_URI=mongodb://localhost:27017
    restart: always

### Another option for gateway
### Can be used instead of traefik
#  gateway:
#    image: fabiolb/fabio:1.5.8-go1.10
#    ports:
#      - "9998:9998" # GUI/management
#      - "8080:9999" # HTTP exposed
#    environment:
#      - FABIO_REGISTRY_CONSUL_ADDR=registry:8500
#      - FABIO_REGISTRY_CONSUL_REGISTER_NAME=gateway
#      - FABIO_PROXY_ADDR=:9999;rt=300s;wt=300s
#    restart: always



  gateway:
    image: traefik:1.6.3
    ports:
      - "8080:8080" # HTTP exposed
#      - "8081:8081" # HTTP Administration exposed
    command:
      - --consulcatalog.endpoint=registry:8500
      - --defaultEntryPoints=http
      - --entryPoints=Name:http Address::8080
      - --web
      - --web.address=:8081
    restart: always

  index:
    image: reportportal/service-index:4.2.0
    environment:
      - RP_SERVER_PORT=8080
      - RP_PROXY_CONSUL=true
    depends_on:
       - registry
       - gateway
    restart: always

  api:
    image: reportportal/service-api:4.2.1
#    depends_on:
#      - mongodb
    environment:
      - RP_PROFILES=docker
      - JAVA_OPTS=-Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp
      - RP_MONGO_URI=mongodb://localhost:27017
    restart: always

  ui:
    image: reportportal/service-ui:4.2.2
    environment:
      - RP_SERVER.PORT=8080
      - RP_CONSUL.TAGS=urlprefix-/ui opts strip=/ui
      - RP_CONSUL.ADDRESS=registry:8500
    restart: always

  analyzer:
    image: reportportal/service-analyzer:4.2.0
    depends_on:
       - registry
       - gateway
       - elasticsearch
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1
    restart: always
    volumes:
        - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    ports:
#        - "9200:9200"

#  jira:
#    image: reportportal/service-jira:4.2.0
#    environment:
#      - RP_PROFILES=docker
#      - RP_MONGO_URI=mongodb://localhost:27017
#    restart: always

#  rally:
#    image: reportportal/service-rally:4.2.0
#    environment:
#      - RP_PROFILES=docker
#     - RP_MONGO_URI=mongodb://localhost:27017
#    restart: always
```
