### ISSUE TITLE
Deploy reportportal with remote MongoDB -  Login page is throwing error

### ISSUE THREAD

**Issue by mcafeerun** [reportportal/reportportal#443]
I deployed reportportal with remote mongoDB host. I see app has been built successfully. But while login to portal, i'm getting following error. What kind of permission did reportportal app need to access remote mongoDB host. Right now, i setup remote mongoDB without any credentials (no auth). 

`An error occurred while connecting to server : You do not have enough permissions. Command execution failed: Error [The 'cursor' option is required, except for aggregate with the explain argument], Command = "aggregate" : "project" , "pipeline" : [ "$unwind" : "$users" , "$match" : "users.login" : "superadmin" , "$group" : "_id" : "$users.login" , "projects" : "$push" : "project" : "$_id" , "projectRole" : "$users.projectRole" , "$lookup" : "from" : "user" , "localField" : "_id" , "foreignField" : "_id" , "as" : "user"]; nested exception is com.mongodb.MongoCommandException: Command failed with error 9: 'The 'cursor' option is required, except for aggregate with the explain argument' on server remotehost.domain.com:27017. The full response is "ok" : 0.0, "errmsg" : "The 'cursor' option is required, except for aggregate with the explain argument", "code" : 9, "codeName" : "FailedToParse"`

$ docker-compose ps
```
            Name                          Command               State                                              Ports
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
reportportal_analyzer_1        /service-analyzer                Up      8080/tcp
reportportal_api_1             /start.sh                        Up      8080/tcp
reportportal_elasticsearch_1   /usr/local/bin/docker-entr ...   Up      9200/tcp, 9300/tcp
reportportal_gateway_1         /traefik --consulcatalog.e ...   Up      80/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8081->8081/tcp
reportportal_index_1           /service-index                   Up      8080/tcp
reportportal_rally_1           /start.sh                        Up      8080/tcp
reportportal_registry_1        docker-entrypoint.sh agent ...   Up      8300/tcp, 8301/tcp, 8301/udp, 8302/tcp, 8302/udp, 0.0.0.0:8500->8500/tcp, 8600/tcp, 8600/udp
reportportal_uat_1             /start.sh                        Up      8080/tcp
reportportal_ui_1              /service-ui                      Up      8080/tcp

```

**Remote MongoDB:**
I see reportPortal has created mongo collection in the remote mongoDB host. 

![image](https://user-images.githubusercontent.com/36393899/42589694-d9eb1e0c-850f-11e8-9eab-76c286b172d2.png)

docker-compose.yml

```
version: '2'
services:
  registry:
    image: 'consul:1.0.6'
    volumes:
      - './data/consul:/consul/data'
    ports:
      - '8500:8500'
    command: agent -server -bootstrap-expect=1 -ui -client 0.0.0.0
    environment:
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    restart: always
  uat:
    image: 'reportportal/service-authorization:4.2.0'
    environment:
      - RP_PROFILES=docker
      - RP_SESSION_LIVE=86400
      - >-
        RP_MONGO_URI=mongodb://remotehost.domain.com:27017/reportportal?authSource=reportportal
    restart: always
  gateway:
    image: 'traefik:1.5'
    ports:
      - '8080:8080'
      - '8081:8081'
    command:
      - '--consulcatalog.endpoint=registry:8500'
      - '--defaultEntryPoints=http'
      - '--entryPoints=Name:http Address::8080'
      - '--logLevel=DEBUG'
      - '--web'
      - '--web.address=:8081'
    restart: always
  index:
    image: 'reportportal/service-index:4.2.0'
    environment:
      - RP_SERVER_PORT=8080
      - RP_PROXY_CONSUL=true
    depends_on:
      - registry
      - gateway
    restart: always
  api:
    image: 'reportportal/service-api:4.2.1'
    environment:
      - RP_PROFILES=docker
      - 'JAVA_OPTS=-Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp'
      - >-
        RP_MONGO_URI=mongodb://remotehost.domain.com:27017/reportportal?authSource=reportportal
    restart: always
  ui:
    image: 'reportportal/service-ui:4.2.2'
    environment:
      - RP_SERVER.PORT=8080
      - RP_CONSUL.TAGS=urlprefix-/ui opts strip=/ui
      - 'RP_CONSUL.ADDRESS=registry:8500'
    restart: always
  analyzer:
    image: 'reportportal/service-analyzer:4.2.0'
    depends_on:
      - registry
      - gateway
      - elasticsearch
    restart: always
  elasticsearch:
    image: 'elastic/elasticsearch:6.1.1'
    restart: always
    volumes:
      - './data/elasticsearch:/usr/share/elasticsearch/data'
    environment:
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
  rally:
    image: 'reportportal/service-rally:4.2.0'
    environment:
      - RP_PROFILES=docker
      - >-
        RP_MONGO_URI=mongodb://remotehost.domain.com:27017/reportportal?authSource=reportportal
    restart: always

```

Note: remotehost.domain.com is a masked name. Due to security reasons.
