### ISSUE TITLE
elasticsearch service failed to start 

### ISSUE THREAD

**Issue by mcafeerun** [reportportal/reportportal#500]
Reportportal elasticsearch service failed to start. 

Note: I did followed all the solution provided in issue [https://github.com/reportportal/service-analyzer/issues/19]. 

Creating this ticket in this main repo, so that i will get some help.

$ docker ps
```
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                         PORTS                                                                      NAMES
265c2223e118        reportportal/service-analyzer:4.2.0        "/service-analyzer"      43 seconds ago      Up 40 seconds                  8080/tcp                                                                   reportportal_analyzer_1
1b4105f3e842        reportportal/service-index:4.2.0           "/service-index"         43 seconds ago      Up 40 seconds                  8080/tcp                                                                   reportportal_index_1
196731a5db69        traefik:1.5                                "/traefik --consul..."   45 seconds ago      Up 42 seconds                  80/tcp, 0.0.0.0:8080-8081->8080-8081/tcp                                   reportportal_gateway_1
7294fe5bd325        reportportal/service-ui:4.2.2              "/service-ui"            45 seconds ago      Up 43 seconds                  8080/tcp                                                                   reportportal_ui_1
97d5e5275c72        consul:1.0.6                               "docker-entrypoint..."   45 seconds ago      Up 43 seconds                  8300-8302/tcp, 8301-8302/udp, 8600/tcp, 8600/udp, 0.0.0.0:8500->8500/tcp   reportportal_registry_1
fb7e595337c9        reportportal/service-api:4.2.1             "/start.sh"              45 seconds ago      Up 43 seconds                  8080/tcp                                                                   reportportal_api_1
36b5f5737924        reportportal/service-rally:4.2.0           "/start.sh"              45 seconds ago      Up 43 seconds                  8080/tcp                                                                   reportportal_rally_1
4fdca72fd329        elastic/elasticsearch:6.1.1                "/usr/local/bin/do..."   45 seconds ago      Restarting (1) 2 seconds ago                                                                              reportportal_elasticsearch_1
4e927db90a67        reportportal/service-authorization:4.2.0   "/start.sh"              45 seconds ago      Up 42 seconds                  8080/tcp 
```

$ docker-compose -p reportportal logs --tail="all" analyzer
```
Attaching to reportportal_analyzer_1
analyzer_1       | 2018/10/05 02:11:19 Service Registered!
analyzer_1       | 2018/10/05 02:11:19 Starting on port 8080
analyzer_1       | [2018-10-05 02:11:22] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.7:9200: connect: connection refused
analyzer_1       | [2018-10-05 02:11:27] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.7:9200: connect: connection refused
analyzer_1       | [2018-10-05 02:11:32] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.7:9200: connect: connection refused
analyzer_1       | [2018-10-05 02:11:37] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.7:9200: connect: connection refused
analyzer_1       | [2018-10-05 02:11:42] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.7:9200: connect: connection refused
analyzer_1       | [2018-10-05 02:11:48] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.7:9200: connect: connection refused
analyzer_1       | [2018-10-05 02:11:53] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp: lookup elasticsearch on 127.0.0.11:53: server misbehaving
analyzer_1       | [2018-10-05 02:11:58] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp: lookup elasticsearch on 127.0.0.11:53: server misbehaving
analyzer_1       | [2018-10-05 02:12:03] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp: lookup elasticsearch on 127.0.0.11:53: server misbehaving
analyzer_1       | [2018-10-05 02:12:08] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp: lookup elasticsearch on 127.0.0.11:53: server misbehaving
```

$ docker-compose -p reportportal logs --tail="all" elasticsearch
```
Attaching to reportportal_elasticsearch_1
elasticsearch_1  | [2018-10-05T02:11:14,325][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1  | [2018-10-05T02:11:14,340][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  | Caused by: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      ... 6 more
elasticsearch_1  | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
elasticsearch_1  |      at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
elasticsearch_1  |      at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_151]
elasticsearch_1  |      at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_151]
elasticsearch_1  |      at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_151]
elasticsearch_1  |      at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:204) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:263) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.1.jar:6.1.1]

```

docker-compose.yml

```
version: '2'
services:
  registry:
    image: 'consul:1.0.6'
    volumes:
      - './data/consul:/consul/data'
    ports:
      - '8500:8500'
    command: agent -server -bootstrap-expect=1 -ui -client 0.0.0.0
    environment:
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    restart: always
  uat:
    image: 'reportportal/service-authorization:4.2.0'
    environment:
      - RP_PROFILES=docker
      - RP_SESSION_LIVE=86400
      - >-
        RP_MONGO_URI=mongodb://remote.host:27017/reportportal?authSource=reportportal
    restart: always
  gateway:
    image: 'traefik:1.5'
    ports:
      - '8080:8080'
      - '8081:8081'
    command:
      - '--consulcatalog.endpoint=registry:8500'
      - '--defaultEntryPoints=http'
      - '--entryPoints=Name:http Address::8080'
      - '--logLevel=DEBUG'
      - '--web'
      - '--web.address=:8081'
    restart: always
  index:
    image: 'reportportal/service-index:4.2.0'
    environment:
      - RP_SERVER_PORT=8080
      - RP_PROXY_CONSUL=true
    depends_on:
      - registry
      - gateway
    restart: always
  api:
    image: 'reportportal/service-api:4.2.1'
    environment:
      - RP_PROFILES=docker
      - 'JAVA_OPTS=-Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp'
      - >-
        RP_MONGO_URI=mongodb://remote.host:27017/reportportal?authSource=reportportal
    restart: always
  ui:
    image: 'reportportal/service-ui:4.2.2'
    environment:
      - RP_SERVER.PORT=8080
      - RP_CONSUL.TAGS=urlprefix-/ui opts strip=/ui
      - 'RP_CONSUL.ADDRESS=registry:8500'
    restart: always
  analyzer:
    image: 'reportportal/service-analyzer:4.2.0'
    depends_on:
      - registry
      - gateway
      - elasticsearch
    restart: always
  elasticsearch:
    image: 'elastic/elasticsearch:6.1.1'
    user: root
    ports:
        - '9200:9200'
    restart: always
    volumes:
      - './data/elasticsearch:/usr/share/elasticsearch/data'
    environment:
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
  rally:
    image: 'reportportal/service-rally:4.2.0'
    environment:
      - RP_PROFILES=docker
      - >-
        RP_MONGO_URI=mongodb://remotehost:27017/reportportal?authSource=reportportal
    restart: always
```
Note: remotehost:27017 is a masked name.
