### ISSUE TITLE
Getting a MongobeeException when trying to start pointing to hosted mongo instance

### ISSUE THREAD

**Issue by randomsync** [reportportal/reportportal#584]
**Describe the bug**
We're trying to launch report portal pointing to a hosted mongo instance in Atlas. The API instance fails to come up. We have updated the docker-compose file to point to the mongo instance:

```
  uat:
    image: 'reportportal/service-authorization:4.2.0'
    environment:
      - RP_PROFILES=docker
      - RP_SESSION_LIVE=86400
      - >-
        RP_MONGO_URI=mongodb://user:password@xyz-reportportal-shard-00-00.mongodb.net:27017,xyz-reportportal-shard-00-01.mongodb.net:27017,xyz-reportportal-shard-00-02.mongodb.net:27017/reportportal?replicaSet=reportportal-shard-0&authSource=admin&ssl=true
    restart: always
...
  api:
    image: 'reportportal/service-api:4.3.4'
    environment:
      - RP_PROFILES=docker
      - 'JAVA_OPTS=-Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp'
      - >-
        RP_MONGO_URI=mongodb://user:password@xyz-reportportal-shard-00-00.mongodb.net:27017,xyz-reportportal-shard-00-01.mongodb.net:27017,xyz-reportportal-shard-00-02.mongodb.net:27017/reportportal?replicaSet=reportportal-shard-0&authSource=admin&ssl=true
    restart: always

```

Here's the snippet of exception:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mongobee' defined in class path resource [com/epam/ta/reportportal/core/configs/MigrationConfiguration.class]: Invocation of init method failed; nested exception is com.github.mongobee.exception.MongobeeException: Command failed with error 13: 'not authorized on reportportal to execute command { $eval: "db.user.find({}).forEach(function(user){
        var userId = user._id
        var user = {
            userId : {
                    "proposedRole" ...", args: [] }' on server xyz-reportportal-shard-00-00.mongodb.net:27017. The full response is { "ok" : 0.0, "errmsg" : "not authorized on reportportal to execute command { $eval: \"db.user.find({}).forEach(function(user){\n        var userId = user._id\n        var user = {\n            userId : {\n                    \"proposedRole\" ...\", args: [] }", "code" : 13, "codeName" : "Unauthorized" }
```

**Expected behavior**
Report portal to start up and function correctly

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is]

NOTE: I've redacted user/password and host names for Mongo, but confirmed that I'm able to connect using mongo shell. I also see some of the collections that report portal created on initialization.
