### ISSUE TITLE
OpenShift/OKD support in Helm charts

### ISSUE THREAD

**Issue by scphantm** [reportportal/reportportal#715]
**Describe the bug**
In V4, you had a service called Gateway.  That service doesn't appear to exist in v5.  This is a problem for OKD/OpenShift users.

OKD is geared towards Enterprise installs, not cloud.  Its ingress and security systems are different to deal with enterprise problems.  One of the problems is typically enterprises already have load balance equipment.  So RedHat deprecated the `ingress` system and replaced it with `routes`.  Where routes are different in that they are very simple so they can be translated into rules that are applied to F5's or whatever you are load balancing.  When you install a base OKD cluster, the default route node is a HA Proxy pod.  Raw Kubernetes uses ngnix as its ingress server, so your ingress patterns are actually ngnix path rewrites.  

The problem is that ingress and routes are not interchangeable.  a route can only have one url pattern per route, where as ingress can have multiple.  you deal with sub folder service routing by creating multiple routes, each with a different url path.  

The issue is simple.  Because there is no more gateway service, you set up 4 routes in OKD

```
route_ui
    path: /ui
    service: ui
route_api
    path: /api
    service: api
route_uat
    path: /uat
    service: uat
route_root
    path: /
    service: ?
```
there is nothing in the app that we can point the root too.  What happens when you point the root to the UI, is it appears the UI service automatically redirects to the /ui folder, this apparently looks different to the UI service and it again tries to redirect to the /ui service.  this causes a redirect loop and the browser kills it.  

Since we have no intention of installing an ingress pod in our cluster (which would be common with your enterprise clients), it appears that Panasas can't use V5.

**Comment by cameronbraid** [comment]
I'm running into the same issue

**Comment by cameronbraid** [comment]
Could we just deploy traefik in a pod and configure it with a file ?
Something like : https://github.com/philall/openshift-traefik

**Comment by DzmitryHumianiuk** [comment]
@avarabyeu assuming concerns above, can we make ui as a root path?

**Comment by avarabyeu** [comment]
@cameronbraid @scphantm Traefik/gateway service is still there:
https://github.com/reportportal/reportportal/blob/master/docker-compose-v5.yml#L17

**Comment by cameronbraid** [comment]
FYI I managed to get it working with traefik 2.0 on openshift

Here's the configmap :

```
apiVersion: v1
data:
  traefik-dynamic-config.yml: |
    http:
        middlewares:
          strip-ui:
            stripPrefix:
              prefixes:
                - "/ui"
              forceSlash: false
          strip-api:
            stripPrefix:
              prefixes:
                - "/api"
              forceSlash: false
          strip-uat:
            stripPrefix:
              prefixes:
                - "/uat"
              forceSlash: false
        
        routers:
          index-router:
            rule: "Path(`/`)"
            service: "index"
          ui-router:
            rule: "PathPrefix(`/ui`)"
            middlewares:
            - strip-ui
            service: "ui"
          uat-router:
            rule: "PathPrefix(`/uat`)"
            middlewares:
            - strip-uat
            service: "uat"
          api-router:
            rule: "PathPrefix(`/api`)"
            middlewares:
            - strip-api
            service: "api"
        
        services:
          uat:
            loadBalancer:
              servers:
              - url: "http://reportportal-uat.reportportal.svc.cluster.local:9999/"
        
          index:
            loadBalancer:
              servers:
              - url: "http://reportportal-index.reportportal.svc.cluster.local:8080/"
        
          api:
            loadBalancer:
              servers:
              - url: "http://reportportal-api.reportportal.svc.cluster.local:8585/"
        
          ui:
            loadBalancer:
              servers:
              - url: "http://reportportal-ui.reportportal.svc.cluster.local:8080/"
  traefik.yml: |
    api:
      dashboard: true
      insecure: true
      
    entryPoints:
      http:
       address: ":8081"

    log:
      level : DEBUG

    accessLog: {}

    providers:
      file:
        filename: /etc/traefik/traefik-dynamic-config.yml
kind: ConfigMap
metadata:
  name: traefik
  namespace: reportportal
```

and the deployment :

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reportportal
    release: reportportal
  name: reportportal-traefik
  namespace: reportportal
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: reportportal-traefik
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: reportportal-traefik
    spec:
      containers:
        - image: 'traefik:v2.0'
          imagePullPolicy: IfNotPresent
          name: traefik
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/traefik/
              name: traefik-config
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: reportportal
      serviceAccountName: reportportal
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: traefik
          name: traefik-config

```

**Comment by cameronbraid** [comment]
and service :

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reportportal
    release: reportportal
  name: reportportal-traefik
  namespace: reportportal
spec:
  ports:
    - name: dashboard
      port: 8088
      protocol: TCP
      targetPort: 8080
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    component: reportportal-traefik
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

and route for app :
```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: reportportal
    release: reportportal
  name: reportportal-traefik
  namespace: reportportal
spec:
  host: MY_HOST
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: reportportal-traefik
    weight: 100
  wildcardPolicy: None
```

and route for dashboard (insecure)

```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: reportportal
    release: reportportal
  name: reportportal-traefik-dashboard
  namespace: reportportal
spec:
  host: MY_DASHBOARD_HOST
  port:
    targetPort: dashboard
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: reportportal-traefik
    weight: 100
  wildcardPolicy: None

```
