### ISSUE TITLE
Migration from 4.3.7 to 5.0 FAILED [v5]

### ISSUE THREAD

**Issue by akrush24** [reportportal/reportportal#860]
**Migration from 4.3.7 to 5.0 does not pass.**
I have reportportal version 4.3.7
![image](https://user-images.githubusercontent.com/3369193/76990176-9705ce00-6958-11ea-8eae-2a1cc8614c67.png)
![image](https://user-images.githubusercontent.com/3369193/76990314-cfa5a780-6958-11ea-9f5c-daee228222f1.png)

I want to upgrade it to 5.0
1. I performed `docker-compose -f ./docker-compose_v5.yml -p reportportal up -d --force-recreate`
when docker-compose_v5.yml is https://github.com/reportportal/reportportal/blob/master/docker-compose.yml
2. I performed upgrade `docker-compose -f ./settings-migration.yml -p reportportal up -d --force-recreate`.
This step is failed for me:

my **docker_composer** file **settings-migration**.yml is:
```
version: '2.4'
services:
  settings-migration:
    image: reportportal/settings-migration:latest
    environment:
      # Postgres params
      RP_DB_HOST: postgres # Where PostgreSQL is hosted
      RP_DB_USER: rpuser   # User for reportportal db
      RP_DB_PASS: rppass   # Password for reportportal db
      RP_DB_NAME: reportportal # The name of reportportal db
      RP_DB_PORT: 5432 # PostgresSQL port
      RP_LAUNCH_KEEPATTR: '6 months' # default config for new cleaning launches job. available values: '2 weeks', '1 month', '3 months',  '6 months'. Can be changed via UI further.
      RP_BINARYSTORE_TYPE: minio
      RP_BINARYSTORE_MINIO_ENDPOINT: http://minio:9000
      RP_BINARYSTORE_MINIO_ACCESSKEY: minio
      RP_BINARYSTORE_MINIO_SECRETKEY: minio123
      ## Users last login date older than ISO_LOCAL_DATE (yyyy-MM-dd) will not migrate
      RP_USER_KEEPFROM: '2000-01-01'
      # Mongodb params
      RP_MONGODB_URI: mongodb://mongodb:27017/reportportal
```

**PostgreSQL logs** after run migration is:

```
2020-03-18 13:00:10.543 UTC [158] ERROR:  duplicate key value violates unique constraint "unique_uk_2"
2020-03-18 13:00:10.543 UTC [158] DETAIL:  Key (class)=(com.epam.ta.reportportal.entity.filter.UserFilter) already exists.
2020-03-18 13:00:10.543 UTC [158] STATEMENT:  INSERT INTO acl_class (class, class_id_type) VALUES ('com.epam.ta.reportportal.entity.filter.UserFilter','java.lang.Long') RETURNING id
```

in postgresql the table **batch_step_execution** contains:
 step_name = user -> COMPLETED
 step_name = project -> FAILED
![image](https://user-images.githubusercontent.com/3369193/76989640-be0fd000-6957-11ea-8c81-c5234ffe36e1.png)

field **exit_message** in **batch_step_execution** is:
```java.lang.NullPointerException
	at org.bson.BasicBSONObject.putAll(BasicBSONObject.java:314)
	at com.epam.reportportal.migration.steps.projects.ProjectItemWriter.writeProjectConfiguration(ProjectItemWriter.java:133)
	at com.epam.reportportal.migration.steps.projects.ProjectItemWriter.lambda$write$0(ProjectItemWriter.java:72)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Unknown Source)
	at com.epam.reportportal.migration.steps.projects.ProjectItemWriter.write(ProjectItemWriter.java:68)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.writeItems(SimpleChunkProcessor.java:175)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.doWrite(SimpleChunkProcessor.java:151)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.write(SimpleChunkProcessor.java:274)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:199)
	at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:75)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:271)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81)
	at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplate$ExecutingRunnable.run(TaskExecutorRepeatTemplate.java:262)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Please help me solve my problem and update the version while saving all my settings and data

**Comment by pbortnik** [comment]
Hi, can you execute some commands in mongo 
`db.getCollection('dbchangelog').find({"changeId" : "v4.2-Introduce default analyzer parameters for each project"})`
`db.getCollection('project').find({"configuration.analyzerConfig" : {$exists : false}})`
Do you have something in response?

**Comment by akrush24** [comment]
Hi.
`> db.getCollection('dbchangelog').find({"changeId" : "v4.2-Introduce default analyzer parameters for each project"})
{ "_id" : ObjectId("5b868b3436d1a00001bb789b"), "changeId" : "v4.2-Introduce default analyzer parameters for each project", "author" : "pbortnik", "timestamp" : ISODate("2018-08-29T12:01:56.958Z"), "changeLogClass" : "com.epam.ta.reportportal.migration.ChangeSets_4_0", "changeSetMethod" : "introduceAnalyzerParameters" }`

`> db.getCollection('project').find({"configuration.analyzerConfig" : {$exists : false}})
{ "_id" : "aqa_personal", "_class" : "com.epam.ta.reportportal.database.entity.Project", "addInfo" : "Personal project of RP Aqa", "configuration" : { "statisticsCalculationStrategy" : "STEP_BASED", "externalSystem" : [ ], "entryType" : "PERSONAL", "projectSpecific" : "DEFAULT", "interruptJobTime" : "1 day", "keepLogs" : "3 months", "keepScreenshots" : "2 weeks", "isAutoAnalyzerEnabled" : false, "subTypes" : { "SYSTEM_ISSUE" : [ { "locator" : "SI001", "typeRef" : "SYSTEM_ISSUE", "longName" : "System Issue", "shortName" : "SI", "hexColor" : "#0274d1" } ], "TO_INVESTIGATE" : [ { "locator" : "TI001", "typeRef" : "TO_INVESTIGATE", "longName" : "To Investigate", "shortName" : "TI", "hexColor" : "#ffb743" } ], "AUTOMATION_BUG" : [ { "locator" : "AB001", "typeRef" : "AUTOMATION_BUG", "longName" : "Automation Bug", "shortName" : "AB", "hexColor" : "#f7d63e" } ], "NO_DEFECT" : [ { "locator" : "ND001", "typeRef" : "NO_DEFECT", "longName" : "No Defect", "shortName" : "ND", "hexColor" : "#777777" } ], "PRODUCT_BUG" : [ { "locator" : "PB001", "typeRef" : "PRODUCT_BUG", "longName" : "Product Bug", "shortName" : "PB", "hexColor" : "#ec3900" } ] }, "emailConfig" : { "emailEnabled" : false, "from" : "reportportal@example.com", "emailCases" : [ { "recipients" : [ "OWNER" ], "sendCase" : "ALWAYS", "launchNames" : [ ], "tags" : [ ] } ] } }, "users" : [ { "login" : "aqa", "proposedRole" : "PROJECT_MANAGER", "projectRole" : "PROJECT_MANAGER" } ], "creationDate" : ISODate("2017-10-25T12:00:44.507Z") }`

**Comment by evjlobanova** [comment]
@pbortnik, please look

**Comment by art-shutter** [comment]
Hi, everyone!
Is there any chance to get an update on the issue? I seem to have stumbled into a similar case.

**Comment by pbortnik** [comment]
Hi,
1. Make sure, that you have version 4.3.11 of api.
2. Execute the next command against Mongodb 
`    
db.getCollection(‘dbchangelog’).deleteOne({“changeId” : “v4.2-Introduce default analyzer parameters for each project”})
`
3. Restart the api of ReportPortal 4
4. Clean up ReportPortal 5 as i mentioned [here](https://github.com/reportportal/reportportal/wiki/Migration-to-ReportPortal-v.5#5-problems-solving)
5. Restart migration

**Comment by akrush24** [comment]
Thanks for the answer

1. version in "4.3.11"
```
# docker ps --filter "name=reportportal.api"
CONTAINER ID        IMAGE                             COMMAND             CREATED             STATUS              PORTS               NAMES
63bbae522d82        reportportal/service-api:4.3.11   "/start.sh"         4 minutes ago       Up 4 minutes        8080/tcp            reportportal.api
```

2. I executed the command, no result
```
> db.getCollection('dbchangelog').deleteOne({"changeId" : "v4.2-Introduce default analyzer parameters for each project"})
{ "acknowledged" : true, "deletedCount" : 0 }
```

3. passed 
```
# docker restart reportportal.api
```

4. then I launch сlean ReportPortal v5
<details>
<summary># docker-compose -f ./docker-compose_v5.yml -p reportportal up -d --force-recreate</summary>

```
WARNING: Found orphan containers (reportportal.registry, reportportal.mongodb, reportportal.jira) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Recreating reportportal.elasticsearch ... done
Creating reportportal_rabbitmq_1      ... done
Creating reportportal_minio_1         ... done
Creating reportportal_postgres_1      ... done
Recreating reportportal.gateway       ... done
Recreating reportportal.uat           ... done
Recreating reportportal.ui            ... done
Recreating reportportal.index         ... done
Recreating reportportal.analyzer      ... done
Creating reportportal_db-scripts_1    ... done
Recreating reportportal.api           ... done
```

</details>

<details>
<summary># docker ps -a</summary>

```
CONTAINER ID        IMAGE                                                     COMMAND                  CREATED              STATUS                          PORTS                                                                      NAMES
16a7fc441603        reportportal/service-api:5.0.0                            "/start.sh"              46 seconds ago       Up 45 seconds                   8080/tcp                                                                   reportportal_api_1
627f1cf15246        reportportal/migrations:5.0.0                             "/entrypoint.sh up"      About a minute ago   Exited (0) About a minute ago                                                                              reportportal_db-scripts_1
c5b31ddfb822        reportportal/service-analyzer:5.0.0                       "/service-analyzer"      About a minute ago   Up 12 seconds                   8080/tcp                                                                   reportportal_analyzer_1
fd76ac0a6a4e        reportportal/service-index:5.0.5                          "/service-index"         About a minute ago   Up About a minute               8080/tcp                                                                   reportportal_index_1
9fe93b2c39b7        docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.0   "/usr/local/bin/dock…"   About a minute ago   Up About a minute (healthy)     9200/tcp, 9300/tcp                                                         reportportal_elasticsearch_1
1dddc4676d12        traefik:1.7.12                                            "/traefik --docker -…"   About a minute ago   Up About a minute               80/tcp, 0.0.0.0:8080-8081->8080-8081/tcp                                   reportportal_gateway_1
d752aba2cd9b        reportportal/service-authorization:5.0.0                  "/start.sh"              About a minute ago   Up About a minute               8080/tcp                                                                   reportportal_uat_1
cd1a4a2bc2c8        reportportal/service-ui:5.0.0                             "/service-ui"            About a minute ago   Up About a minute               8080/tcp                                                                   reportportal_ui_1
34905f5594ea        postgres:12-alpine                                        "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)     0.0.0.0:5432->5432/tcp                                                     reportportal_postgres_1
0edd511629f4        minio/minio:RELEASE.2020-05-01T22-19-14Z                  "/usr/bin/docker-ent…"   About a minute ago   Up About a minute (healthy)     0.0.0.0:9000->9000/tcp                                                     reportportal_minio_1
a51ac10a7c9f        rabbitmq:3.7.16-management                                "docker-entrypoint.s…"   About a minute ago   Up About a minute (healthy)     4369/tcp, 5671-5672/tcp, 15671/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp    reportportal_rabbitmq_1
f4d04ab911a9        consul:1.0.6                                              "docker-entrypoint.s…"   3 minutes ago        Up 3 minutes                    8300-8302/tcp, 8301-8302/udp, 8600/tcp, 8600/udp, 0.0.0.0:8500->8500/tcp   reportportal.registry
26375c55812b        mongo:3.4                                                 "docker-entrypoint.s…"   3 minutes ago        Up 3 minutes                    0.0.0.0:27017->27017/tcp                                                   reportportal.mongodb
d7814bec3c7f        reportportal/service-jira:4.3.0                           "/start.sh"              3 minutes ago        Up 3 minutes                    8080/tcp                                                                   reportportal.jira
```

</details>

<details>
<summary># cat docker-compose_v5.yml</summary>

```
## You can generate a custom docker compose file automatically on http://reportportal.io/download (Step 2)

## This is example of Docker Compose for ReportPortal
## Do not forget to configure data volumes for production usage

## Execute 'docker-compose -f docker-compose.yml -p reportportal up -d --force-recreate' --build
## to start all containers in daemon mode
## Where:
##      '-f docker-compose.yml' -- specifies this compose file
##      '-p reportportal' -- specifies container's prefix (project name)
##      '-d' -- enables daemon mode
##      '--force-recreate' -- forces re-recreating of all containers

version: '2.4'
services:

  gateway:
    image: traefik:1.7.12
    ports:
      - "8080:8080" # HTTP exposed
      - "8081:8081" # HTTP Administration exposed
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --docker
      - --docker.watch
      - --docker.constraints=tag==reportportal
      - --defaultEntryPoints=http
      - --entryPoints=Name:http Address::8080
      - --logLevel=ERROR
      - --web
      - --web.address=:8081
      - --web.metrics=true
      - --web.metrics.prometheus=true
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.0
    restart: always
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "logger.level=INFO"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
      # ports:
      # - "9200:9200"
    healthcheck:
      test: ["CMD", "curl","-s" ,"-f", "http://localhost:9200/_cat/health"]

  analyzer:
    image: reportportal/service-analyzer:5.0.0
    depends_on:
      - rabbitmq
      - elasticsearch
    restart: always

  ### initial db schema for reportportal
  db-scripts:
    image: reportportal/migrations:5.0.0
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: reportportal
      POSTGRES_USER: rpuser
      POSTGRES_PASSWORD: rppass


  postgres:
    image: postgres:12-alpine
    shm_size: '512m'
    environment:
      POSTGRES_USER: rpuser
      POSTGRES_PASSWORD: rppass
      POSTGRES_DB: reportportal
    volumes:
      # For unix host
      - ./data/postgres:/var/lib/postgresql/data
      # For windows host
      # - postgres:/var/lib/postgresql/data
    restart: on-failure
    # If you need to access the DB locally. Could be a security risk to expose DB.
    ports:
      - "5432:5432"
    command:
      -c checkpoint_completion_target=0.9
      -c work_mem=96MB
      -c wal_writer_delay=20ms
      -c synchronous_commit=off
      -c wal_buffers=32MB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 120s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.7.16-management
    ports:
      # - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      retries: 5

  uat:
    image: reportportal/service-authorization:5.0.0
    #ports:
    #  - "9999:9999"
    environment:
      - RP_DB_USER=rpuser
      - RP_DB_PASS=rppass
      - RP_DB_NAME=reportportal
      - RP_BINARYSTORE_TYPE=minio
      - RP_BINARYSTORE_MINIO_ENDPOINT=http://minio:9000
      - RP_BINARYSTORE_MINIO_ACCESSKEY=minio
      - RP_BINARYSTORE_MINIO_SECRETKEY=minio123
      - RP_SESSION_LIVE=86400 #in seconds
    restart: always
    labels:
      - "traefik.backend=uat"
      - "traefik.frontend.rule=PathPrefixStrip:/uat"
      - "traefik.enable=true"
      - "traefik.port=9999"
      - "traefik.tags=reportportal"

  index:
    image: reportportal/service-index:5.0.5
    depends_on:
      gateway:
        condition: service_started
    restart: always
    environment:
      - LB_URL=http://gateway:8081
    labels:
      - "traefik.backend=index"
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.tags=reportportal"

  api:
    image: reportportal/service-api:5.0.0
    depends_on:
      rabbitmq:
        condition: service_healthy
      gateway:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      - RP_DB_USER=rpuser
      - RP_DB_PASS=rppass
      - RP_DB_NAME=reportportal
      - RP_BINARYSTORE_TYPE=minio
      - RP_BINARYSTORE_MINIO_ENDPOINT=http://minio:9000
      - RP_BINARYSTORE_MINIO_ACCESSKEY=minio
      - RP_BINARYSTORE_MINIO_SECRETKEY=minio123
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=info
      - JAVA_OPTS=-Xmx1g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp  -Dcom.sun.management.jmxremote.rmi.port=12349 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false  -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=10.6.128.241
    restart: always
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.rule=PathPrefixStrip:/api"
      - "traefik.enable=true"
      - "traefik.port=8585"
      - "traefik.tags=reportportal"

  ui:
    image: reportportal/service-ui:5.0.0
    environment:
      - RP_SERVER_PORT=8080
    restart: always
    labels:
      - "traefik.backend=ui"
      - "traefik.frontend.rule=PathPrefixStrip:/ui/"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.tags=reportportal"

  minio:
    image: minio/minio:RELEASE.2020-05-01T22-19-14Z
    ports:
      - '9000:9000'
    volumes:
      - ./data/storage:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Docker volume for Windows host
#volumes:
#  postgres:
```

</details>

5. then I try to run settings migration
<details>
<summary># docker-compose -f ./settings-migration.yml -p reportportal up </summary>

```
WARNING: Found orphan containers (reportportal_api_1, reportportal_analyzer_1, reportportal_index_1, reportportal_minio_1, reportportal_postgres_1, reportportal_elasticsearch_1, reportportal_ui_1, reportportal_uat_1, reportportal_gateway_1, reportportal_rabbitmq_1, reportportal.mongodb) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Starting reportportal_settings-migration_1 ... done
Attaching to reportportal_settings-migration_1
settings-migration_1  | /start.sh: 1: /start.sh: 0!/bin/sh: not found
settings-migration_1  | 
settings-migration_1  |   .   ____          _            __ _ _
settings-migration_1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
settings-migration_1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
settings-migration_1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
settings-migration_1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
settings-migration_1  |  =========|_|==============|___/=/_/_/_/
settings-migration_1  |  :: Spring Boot ::        (v1.5.2.RELEASE)
settings-migration_1  | 
settings-migration_1  | 12-05-2020 11:41:48.075 [main] INFO  com.epam.reportportal.migration.DataMigrationApplication.logStarting - Starting DataMigrationApplication on aa9ba49eaec2 with PID 6 (/app.jar started by root in /)
settings-migration_1  | 12-05-2020 11:41:48.078 [main] INFO  com.epam.reportportal.migration.DataMigrationApplication.logStartupProfileInfo - No active profile set, falling back to default profiles: default
settings-migration_1  | 12-05-2020 11:41:48.120 [main] INFO  org.springframework.context.annotation.AnnotationConfigApplicationContext.prepareRefresh - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@3857f613: startup date [Tue May 12 11:41:48 UTC 2020]; root of context hierarchy
settings-migration_1  | 12-05-2020 11:41:48.486 [main] INFO  org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition - Overriding bean definition for bean 'jobRepository' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration; factoryMethodName=jobRepository; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/batch/core/configuration/annotation/SimpleBatchConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=pgDatasourceConfig; factoryMethodName=jobRepository; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [com/epam/reportportal/migration/PgDatasourceConfig.class]]
settings-migration_1  | 12-05-2020 11:41:48.488 [main] INFO  org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition - Overriding bean definition for bean 'transactionManager' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration; factoryMethodName=transactionManager; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/batch/core/configuration/annotation/SimpleBatchConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=true; factoryBeanName=dataMigrationApplication; factoryMethodName=transactionManager; initMethodName=null; destroyMethodName=(inferred); defined in com.epam.reportportal.migration.DataMigrationApplication]
settings-migration_1  | WARNING: An illegal reflective access operation has occurred
settings-migration_1  | WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/app.jar!/BOOT-INF/lib/spring-core-4.3.7.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
settings-migration_1  | WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
settings-migration_1  | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
settings-migration_1  | WARNING: All illegal access operations will be denied in a future release
settings-migration_1  | 12-05-2020 11:41:48.793 [main] WARN  org.springframework.context.annotation.ConfigurationClassEnhancer.intercept - @Bean method ScopeConfiguration.stepScope is non-static and returns an object assignable to Spring's BeanFactoryPostProcessor interface. This will result in a failure to process annotations such as @Autowired, @Resource and @PostConstruct within the method's declaring @Configuration class. Add the 'static' modifier to this method to avoid these container lifecycle issues; see @Bean javadoc for complete details.
settings-migration_1  | 12-05-2020 11:41:48.803 [main] WARN  org.springframework.context.annotation.ConfigurationClassEnhancer.intercept - @Bean method ScopeConfiguration.jobScope is non-static and returns an object assignable to Spring's BeanFactoryPostProcessor interface. This will result in a failure to process annotations such as @Autowired, @Resource and @PostConstruct within the method's declaring @Configuration class. Add the 'static' modifier to this method to avoid these container lifecycle issues; see @Bean javadoc for complete details.
settings-migration_1  | 12-05-2020 11:41:48.812 [main] INFO  org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.<init> - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
settings-migration_1  | 12-05-2020 11:41:48.910 [main] INFO  org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.initialize - Initializing ExecutorService  'threadPoolTaskExecutor'
settings-migration_1  | 12-05-2020 11:41:48.959 [main] INFO  com.zaxxer.hikari.HikariDataSource.<init> - HikariPool-1 - Started.
settings-migration_1  | 12-05-2020 11:41:49.028 [main] INFO  com.zaxxer.hikari.pool.PoolBase.getAndSetNetworkTimeout - HikariPool-1 - Driver does not support get/set network timeout for connections. (Method org.postgresql.jdbc.PgConnection.getNetworkTimeout() is not yet implemented.)
settings-migration_1  | 12-05-2020 11:41:49.164 [main] INFO  org.springframework.batch.core.repository.support.JobRepositoryFactoryBean.afterPropertiesSet - No database type set, using meta data indicating: POSTGRES
settings-migration_1  | 12-05-2020 11:41:49.517 [main] INFO  org.mongodb.driver.cluster.info - Cluster created with settings {hosts=[mongodb:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
settings-migration_1  | 12-05-2020 11:41:49.612 [cluster-ClusterId{value='5eba8b7d3d18a1000637764b', description='null'}-mongodb:27017] INFO  org.mongodb.driver.connection.info - Opened connection [connectionId{localValue:1, serverValue:4}] to mongodb:27017
settings-migration_1  | 12-05-2020 11:41:49.614 [cluster-ClusterId{value='5eba8b7d3d18a1000637764b', description='null'}-mongodb:27017] INFO  org.mongodb.driver.cluster.info - Monitor thread successfully connected to server with description ServerDescription{address=mongodb:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[3, 4, 24]}, minWireVersion=0, maxWireVersion=5, maxDocumentSize=16777216, roundTripTimeNanos=494685}
settings-migration_1  | 12-05-2020 11:41:50.056 [main] INFO  org.mongodb.driver.connection.info - Opened connection [connectionId{localValue:2, serverValue:5}] to mongodb:27017
settings-migration_1  | 12-05-2020 11:41:50.231 [main] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions - Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
settings-migration_1  | 12-05-2020 11:41:50.297 [main] INFO  org.springframework.jdbc.support.SQLErrorCodesFactory.<init> - SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase, Hana]
settings-migration_1  | 12-05-2020 11:41:50.367 [main] INFO  org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript - Executing SQL script from class path resource [org/springframework/batch/core/schema-postgresql.sql]
settings-migration_1  | 12-05-2020 11:41:50.413 [main] INFO  org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript - Executed SQL script from class path resource [org/springframework/batch/core/schema-postgresql.sql] in 45 ms.
settings-migration_1  | 12-05-2020 11:41:50.493 [main] INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter.afterSingletonsInstantiated - Registering beans for JMX exposure on startup
settings-migration_1  | 12-05-2020 11:41:50.494 [main] INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter.autodetect - Bean with name 'pgDatasourceConfig' has been autodetected for JMX exposure
settings-migration_1  | 12-05-2020 11:41:50.495 [main] INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter.autodetect - Bean with name 'dataSource' has been autodetected for JMX exposure
settings-migration_1  | 12-05-2020 11:41:50.498 [main] INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter.registerBeanInstance - Located MBean 'dataSource': registering with JMX server as MBean [com.zaxxer.hikari:name=dataSource,type=HikariDataSource]
settings-migration_1  | 12-05-2020 11:41:50.500 [main] INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter.registerBeanInstance - Located MBean 'pgDatasourceConfig': registering with JMX server as MBean [com.epam.reportportal.migration:name=pgDatasourceConfig,type=PgDatasourceConfig]
settings-migration_1  | 12-05-2020 11:41:50.508 [main] INFO  org.springframework.boot.autoconfigure.batch.JobLauncherCommandLineRunner.run - Running default command line with: []
settings-migration_1  | 12-05-2020 11:41:50.509 [main] INFO  org.springframework.batch.core.repository.support.JobRepositoryFactoryBean.afterPropertiesSet - No database type set, using meta data indicating: POSTGRES
settings-migration_1  | 12-05-2020 11:41:50.513 [main] INFO  org.springframework.batch.core.launch.support.SimpleJobLauncher.afterPropertiesSet - No TaskExecutor has been set, defaulting to synchronous executor.
settings-migration_1  | 12-05-2020 11:41:50.544 [main] INFO  org.springframework.batch.core.launch.support.SimpleJobLauncher.run - Job: [SimpleJob: [name=settingsMigrationJob]] launched with the following parameters: [{}]
settings-migration_1  | 12-05-2020 11:41:50.550 [main] INFO  org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript - Executing SQL script from class path resource [clean_up_data.sql]
settings-migration_1  | 12-05-2020 11:41:50.557 [main] INFO  org.springframework.jdbc.datasource.init.ScriptUtils.executeSqlScript - Executed SQL script from class path resource [clean_up_data.sql] in 7 ms.
settings-migration_1  | 12-05-2020 11:41:50.565 [main] INFO  org.springframework.batch.core.job.SimpleStepHandler.handleStep - Executing step: [user]
settings-migration_1  | 12-05-2020 11:41:50.622 [threadPoolTaskExecutor-2] INFO  org.mongodb.driver.connection.info - Opened connection [connectionId{localValue:3, serverValue:7}] to mongodb:27017
settings-migration_1  | 12-05-2020 11:41:50.622 [threadPoolTaskExecutor-4] INFO  org.mongodb.driver.connection.info - Opened connection [connectionId{localValue:4, serverValue:6}] to mongodb:27017
settings-migration_1  | 12-05-2020 11:41:51.022 [main] INFO  org.springframework.batch.core.job.SimpleStepHandler.handleStep - Executing step: [project]
settings-migration_1  | 12-05-2020 11:41:51.088 [main] ERROR org.springframework.batch.core.step.AbstractStep.execute - Encountered an error executing step project in job settingsMigrationJob
settings-migration_1  | java.lang.NullPointerException: null
settings-migration_1  |         at org.bson.BasicBSONObject.putAll(BasicBSONObject.java:314)
settings-migration_1  |         at com.epam.reportportal.migration.steps.projects.ProjectItemWriter.writeProjectConfiguration(ProjectItemWriter.java:133)
settings-migration_1  |         at com.epam.reportportal.migration.steps.projects.ProjectItemWriter.lambda$write$0(ProjectItemWriter.java:72)
settings-migration_1  |         at java.base/java.util.ArrayList.forEach(Unknown Source)
settings-migration_1  |         at java.base/java.util.Collections$UnmodifiableCollection.forEach(Unknown Source)
settings-migration_1  |         at com.epam.reportportal.migration.steps.projects.ProjectItemWriter.write(ProjectItemWriter.java:68)
settings-migration_1  |         at org.springframework.batch.core.step.item.SimpleChunkProcessor.writeItems(SimpleChunkProcessor.java:175)
settings-migration_1  |         at org.springframework.batch.core.step.item.SimpleChunkProcessor.doWrite(SimpleChunkProcessor.java:151)
settings-migration_1  |         at org.springframework.batch.core.step.item.SimpleChunkProcessor.write(SimpleChunkProcessor.java:274)
settings-migration_1  |         at org.springframework.batch.core.step.item.SimpleChunkProcessor.process(SimpleChunkProcessor.java:199)
settings-migration_1  |         at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:75)
settings-migration_1  |         at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
settings-migration_1  |         at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
settings-migration_1  |         at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
settings-migration_1  |         at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:271)
settings-migration_1  |         at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:81)
settings-migration_1  |         at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplate$ExecutingRunnable.run(TaskExecutorRepeatTemplate.java:262)
settings-migration_1  |         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
settings-migration_1  |         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
settings-migration_1  |         at java.base/java.lang.Thread.run(Unknown Source)
settings-migration_1  | 12-05-2020 11:41:51.091 [main] INFO  org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.shutdown - Shutting down ExecutorService 'threadPoolTaskExecutor'
settings-migration_1  | 12-05-2020 11:41:51.093 [main] INFO  org.springframework.batch.core.launch.support.SimpleJobLauncher.run - Job: [SimpleJob: [name=settingsMigrationJob]] completed with the following parameters: [{}] and the following status: [FAILED]
settings-migration_1  | 12-05-2020 11:41:51.095 [main] INFO  com.epam.reportportal.migration.DataMigrationApplication.logStarted - Started DataMigrationApplication in 3.438 seconds (JVM running for 3.935)
settings-migration_1  | 12-05-2020 11:41:51.098 [Thread-3] INFO  org.springframework.context.annotation.AnnotationConfigApplicationContext.doClose - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@3857f613: startup date [Tue May 12 11:41:48 UTC 2020]; root of context hierarchy
settings-migration_1  | 12-05-2020 11:41:51.100 [Thread-3] INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter.destroy - Unregistering JMX-exposed beans on shutdown
settings-migration_1  | 12-05-2020 11:41:51.100 [Thread-3] INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter.unregisterBeans - Unregistering JMX-exposed beans
settings-migration_1  | 12-05-2020 11:41:51.102 [Thread-3] INFO  org.mongodb.driver.connection.info - Closed connection [connectionId{localValue:3, serverValue:7}] to mongodb:27017 because the pool has been closed.
settings-migration_1  | 12-05-2020 11:41:51.103 [Thread-3] INFO  org.mongodb.driver.connection.info - Closed connection [connectionId{localValue:4, serverValue:6}] to mongodb:27017 because the pool has been closed.
settings-migration_1  | 12-05-2020 11:41:51.103 [Thread-3] INFO  org.mongodb.driver.connection.info - Closed connection [connectionId{localValue:2, serverValue:5}] to mongodb:27017 because the pool has been closed.
settings-migration_1  | 12-05-2020 11:41:51.104 [Thread-3] INFO  com.zaxxer.hikari.pool.HikariPool.shutdown - HikariPool-1 - Close initiated...
settings-migration_1  | 12-05-2020 11:41:51.109 [Thread-3] INFO  com.zaxxer.hikari.pool.HikariPool.shutdown - HikariPool-1 - Closed.
settings-migration_1  | 12-05-2020 11:41:51.109 [Thread-3] INFO  org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.shutdown - Shutting down ExecutorService 'threadPoolTaskExecutor'
reportportal_settings-migration_1 exited with code 0
```

</details>

Final:
passed migration does not succeed =(
